#!/usr/bin/env python3
"""Generates strict JSON schemas for kubeconform from CustomResourceDefinition manifests.

    deploy/charts/crd-schemas.py <output directory> < crds.yaml

Reads every CustomResourceDefinition in the YAML stream on stdin (other documents are skipped) and
writes one `<kind>_<version>.json` per served version (kind in lower case), the file names that
kubeconform's `-schema-location <dir>/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json` expects.

Strict: every object schema that lists properties, does not preserve unknown fields and does not
declare additionalProperties itself gets `additionalProperties: false`, so a misspelt or unknown
field fails validation. `x-kubernetes-int-or-string` becomes string-or-integer, `nullable` allows
null, and the top level accepts apiVersion, kind and metadata. Needs python3 and PyYAML only.
"""

import copy
import json
import os
import sys

import yaml


def strict(node):
    """Returns a strict JSON schema for an OpenAPI v3 schema node of a CRD."""
    if not isinstance(node, dict):
        return node
    schema = dict(node)
    # Recurse through the schema keywords only: a field may itself be named "properties" or "type".
    if isinstance(schema.get("properties"), dict):
        schema["properties"] = {name: strict(child) for name, child in schema["properties"].items()}
    for keyword in ("items", "additionalProperties", "not"):
        if isinstance(schema.get(keyword), dict):
            schema[keyword] = strict(schema[keyword])
    for keyword in ("allOf", "anyOf", "oneOf"):
        if isinstance(schema.get(keyword), list):
            schema[keyword] = [strict(child) for child in schema[keyword]]
    if schema.pop("x-kubernetes-int-or-string", False):
        schema.pop("type", None)
        schema["oneOf"] = [{"type": "string"}, {"type": "integer"}]
    if schema.pop("nullable", False) and isinstance(schema.get("type"), str):
        schema["type"] = [schema["type"], "null"]
    if ("properties" in schema
            and not schema.get("x-kubernetes-preserve-unknown-fields")
            and "additionalProperties" not in schema):
        schema["additionalProperties"] = False
    return schema


def schemas(crd):
    """Yields (file name, JSON schema) for each served version of a CRD."""
    kind = crd["spec"]["names"]["kind"]
    group = crd["spec"]["group"]
    for version in crd["spec"]["versions"]:
        if not version.get("served", True):
            continue
        openapi = copy.deepcopy(version["schema"]["openAPIV3Schema"])
        properties = openapi.setdefault("properties", {})
        properties.setdefault("apiVersion", {"type": "string"})
        properties.setdefault("kind", {"type": "string"})
        properties.setdefault("metadata", {"type": "object"})
        schema = strict(openapi)
        schema["$schema"] = "http://json-schema.org/schema#"
        schema["description"] = f"{kind} {group}/{version['name']}, generated by crd-schemas.py"
        yield f"{kind.lower()}_{version['name']}.json", schema


def main():
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <output directory> < crds.yaml", file=sys.stderr)
        return 2
    out = sys.argv[1]
    os.makedirs(out, exist_ok=True)
    written = 0
    for doc in yaml.safe_load_all(sys.stdin):
        if not doc or doc.get("kind") != "CustomResourceDefinition":
            continue
        for name, schema in schemas(doc):
            with open(os.path.join(out, name), "w", encoding="utf-8") as handle:
                json.dump(schema, handle, indent=1, sort_keys=True)
            written += 1
    if written == 0:
        print("no CustomResourceDefinition found on stdin", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
