import { existsSync, readFileSync } from 'node:fs';

import { fromRoot, outputPaths, repoRoot } from './paths.ts';
import { constantsOf, loadSpec, type Constant, type ConstantKind, type CryptoSpec } from './spec.ts';
import { buildVectors } from './vectors.ts';

export interface Inputs {
  spec: CryptoSpec;
}

export function loadInputs(root = repoRoot): Inputs {
  return { spec: loadSpec(root) };
}

const REGENERATE = 'pnpm --filter @coldframe/crypto-spec run generate';
const HEADER = 'Generated by packages/crypto-spec/scripts/generate.ts from crypto-spec.json. Do not edit.';
const REGENERATE_HINT = `Regenerate with \`${REGENERATE}\`.`;
const SUMMARY = 'Constants of the Device crypto contract, `packages/crypto-spec/crypto-spec.json` (AD-12, AD-17, AD-25).';

/** `deviceIdHexLength` → `DEVICE_ID_HEX_LENGTH`. */
export function screamingName(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
}

/** `deviceIdHexLength` → `DeviceIdHexLength`. */
export function pascalName(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

/** Splits `text` into lines of at most `width` characters, at spaces. */
function wrap(text: string, width: number): string[] {
  const lines: string[] = [];
  let current = '';
  for (const word of text.split(' ')) {
    const next = current === '' ? word : `${current} ${word}`;
    if (next.length > width && current !== '') {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }
  lines.push(current);
  return lines;
}

/** A string literal that Rust, C# and Kotlin all read the same way (ASCII only). */
function stringLiteral(value: string, escapeDollar = false): string {
  if (!/^[\x20-\x7e\n]*$/.test(value)) {
    throw new Error(`constant value is not printable ASCII: ${JSON.stringify(value)}`);
  }
  const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
  return `"${escapeDollar ? escaped.replace(/\$/g, '\\$') : escaped}"`;
}

function literal(constant: Constant, language: 'rust' | 'csharp' | 'kotlin'): string {
  if (constant.kind === 'str') {
    if (typeof constant.value !== 'string') throw new Error(`${constant.name} must be a string`);
    return stringLiteral(constant.value, language === 'kotlin');
  }
  if (typeof constant.value !== 'number' || !Number.isSafeInteger(constant.value) || constant.value < 0) {
    throw new Error(`${constant.name} must be a non-negative integer`);
  }
  const value = String(constant.value);
  if (language === 'kotlin' && (constant.kind === 'u64' || constant.kind === 'ms')) return `${value}L`;
  if (language === 'csharp' && constant.kind === 'u64') return `${value}UL`;
  if (language === 'csharp' && constant.kind === 'ms') return `${value}L`;
  return value;
}

const RUST_TYPES: Record<ConstantKind, string> = { str: '&str', len: 'usize', u8: 'u8', u16: 'u16', u64: 'u64', ms: 'u64' };
const CSHARP_TYPES: Record<ConstantKind, string> = { str: 'string', len: 'int', u8: 'byte', u16: 'ushort', u64: 'ulong', ms: 'long' };
const KOTLIN_TYPES: Record<ConstantKind, string> = { str: 'String', len: 'Int', u8: 'Int', u16: 'Int', u64: 'Long', ms: 'Long' };

function renderRust(spec: CryptoSpec): string {
  const lines = [`// ${HEADER}`, `// ${REGENERATE_HINT}`, '', ...wrap(SUMMARY, 96).map((line) => `//! ${line}`)];
  for (const group of constantsOf(spec)) {
    lines.push('', `// ${group.title}`);
    for (const constant of group.constants) {
      lines.push('', ...wrap(constant.doc, 96).map((line) => `/// ${line}`));
      lines.push(`pub const ${screamingName(constant.name)}: ${RUST_TYPES[constant.kind]} = ${literal(constant, 'rust')};`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

function renderCsharp(spec: CryptoSpec): string {
  const lines = [
    `// <auto-generated>`,
    `// ${HEADER}`,
    `// ${REGENERATE_HINT}`,
    `// </auto-generated>`,
    '',
    'namespace Coldframe.Crypto;',
    '',
    '/// <summary>',
    ...wrap(SUMMARY, 100).map((line) => `/// ${line}`),
    '/// </summary>',
    'public static class CryptoSpec',
    '{',
  ];
  let first = true;
  for (const group of constantsOf(spec)) {
    if (!first) lines.push('');
    first = false;
    lines.push(`    // ${group.title}`);
    for (const constant of group.constants) {
      lines.push('', '    /// <summary>', ...wrap(constant.doc, 100).map((line) => `    /// ${line}`), '    /// </summary>');
      lines.push(
        `    public const ${CSHARP_TYPES[constant.kind]} ${pascalName(constant.name)} = ${literal(constant, 'csharp')};`,
      );
    }
  }
  lines.push('}', '');
  return lines.join('\n');
}

function renderKotlin(spec: CryptoSpec): string {
  const lines = [
    `// ${HEADER}`,
    `// ${REGENERATE_HINT}`,
    '',
    'package com.escendit.coldframe.core.crypto',
    '',
    '/**',
    ...wrap(SUMMARY, 100).map((line) => ` * ${line}`),
    ' */',
    'public object CryptoSpec {',
  ];
  let first = true;
  for (const group of constantsOf(spec)) {
    if (!first) lines.push('');
    first = false;
    lines.push(`    // ${group.title}`);
    for (const constant of group.constants) {
      const doc = wrap(constant.doc, 100);
      lines.push('');
      if (doc.length === 1) {
        lines.push(`    /** ${doc[0] ?? ''} */`);
      } else {
        lines.push('    /**', ...doc.map((line) => `     * ${line}`), '     */');
      }
      lines.push(`    public const val ${screamingName(constant.name)}: ${KOTLIN_TYPES[constant.kind]} = ${literal(constant, 'kotlin')}`);
    }
  }
  lines.push('}', '');
  return lines.join('\n');
}

/** Every generated file, keyed by its path relative to the repository root. */
export function renderOutputs({ spec }: Inputs): Map<string, string> {
  return new Map<string, string>([
    [outputPaths.vectors, `${JSON.stringify(buildVectors(spec), null, 2)}\n`],
    [outputPaths.rust, renderRust(spec)],
    [outputPaths.csharp, renderCsharp(spec)],
    [outputPaths.kotlin, renderKotlin(spec)],
  ]);
}

/** Paths whose committed content differs from `outputs` or is missing. Empty when everything is fresh. */
export function findStale(root: string, outputs: ReadonlyMap<string, string>): string[] {
  const stale: string[] = [];
  for (const [path, content] of outputs) {
    const file = fromRoot(path, root);
    if (!existsSync(file) || readFileSync(file, 'utf8') !== content) {
      stale.push(path);
    }
  }
  return stale;
}
