/**
 * Builds vectors.json: fixed inputs, outputs computed by the reference implementation, and the RFC
 * anchors copied verbatim from the RFC texts. Byte strings are lowercase hex; 64-bit counters and
 * timestamps are decimal strings so no language loses precision.
 */
import {
  aeadOpen,
  aeadSeal,
  deriveDeviceKeys,
  fingerprint,
  frameAad,
  frameNonce,
  hex,
  heartbeatCanonical,
  hkdf,
  hkdfExtract,
  hmacSha256,
  hpkeSealBase,
  sensorId,
  setupAad,
  setupKeys,
  setupNonce,
  sha256,
  unhex,
  uuidV5,
  x25519,
  x25519PublicKey,
} from './reference.ts';
import type { CryptoSpec } from './spec.ts';

export const VECTORS_COMMENT =
  'Generated by packages/crypto-spec/scripts/generate.ts from crypto-spec.json. Do not edit: run `pnpm --filter @coldframe/crypto-spec run generate`. The anchors are copied verbatim from the RFCs.';

/** RFC test vectors, copied from the RFC texts (never from our own output). */
export const ANCHORS = {
  rfc5869TestCase1: {
    source: 'RFC 5869 Appendix A.1 (HKDF-SHA256, Test Case 1)',
    ikm: '0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b',
    salt: '000102030405060708090a0b0c',
    info: 'f0f1f2f3f4f5f6f7f8f9',
    length: 42,
    prk: '077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5',
    okm: '3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865',
  },
  rfc7748Section61: {
    source: 'RFC 7748 Section 6.1 (X25519)',
    alicePrivate: '77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a',
    alicePublic: '8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a',
    bobPrivate: '5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb',
    bobPublic: 'de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f',
    sharedSecret: '4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742', // gitleaks:allow (RFC 7748 test vector)
  },
  rfc8439Section282: {
    source: 'RFC 8439 Section 2.8.2 (AEAD_CHACHA20_POLY1305)',
    key: '808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f',
    nonce: '070000004041424344454647',
    aad: '50515253c0c1c2c3c4c5c6c7',
    plaintext:
      '4c616469657320616e642047656e746c656d656e206f662074686520636c617373206f66202739393a204966204920636f756c64206f6666657220796f75206f6e6c79206f6e652074697020666f7220746865206675747572652c2073756e73637265656e20776f756c642062652069742e',
    ciphertext:
      'd31a8d34648e60db7b86afbc53ef7ec2a4aded51296e08fea9e2b5a736ee62d63dbea45e8ca9671282fafb69da92728b1a71de0a9e060b2905d6a5b67ecd3b3692ddbd7f2d778b8c9803aee328091b58fab324e4fad675945585808b4831d7bc3ff4def08e4b7a9de576d26586cec64b6116',
    tag: '1ae10b594f09e26a7e902ecbd0600691',
  },
  rfc9180A21: {
    source: 'RFC 9180 Appendix A.2.1 (DHKEM(X25519, HKDF-SHA256), HKDF-SHA256, ChaCha20Poly1305, base mode), first encryption',
    mode: 0,
    kemId: 32,
    kdfId: 1,
    aeadId: 3,
    info: '4f6465206f6e2061204772656369616e2055726e',
    ikmE: '909a9b35d3dc4713a5e72a4da274b55d3d3821a37e5d099e74a647db583a904b',
    skEm: 'f4ec9b33b792c372c1d2c2063507b684ef925b8c75a42dbcbf57d63ccd381600',
    pkEm: '1afa08d3dec047a643885163f1180476fa7ddb54c6a8029ea33f95796bf2ac4a',
    pkRm: '4310ee97d88cc1f088a5576c77ab0cf5c3ac797f3d95139c6c84b5429c59662a',
    skRm: '8057991eef8f1f1af18f4a9491d16a1ce333f695d4db8e38da75975c4478e0fb',
    enc: '1afa08d3dec047a643885163f1180476fa7ddb54c6a8029ea33f95796bf2ac4a',
    sharedSecret: '0bbe78490412b4bbea4812666f7916932b828bba79942424abb65244930d69a7', // gitleaks:allow (RFC 9180 test vector)
    key: 'ad2744de8e17f4ebba575b3f5f5a8fa1f69c2a07f6e7500bc60ca6e3e3ec1c91', // gitleaks:allow (RFC 9180 test vector)
    baseNonce: '5c4d98150661b848853b547f',
    pt: '4265617574792069732074727574682c20747275746820626561757479',
    aad: '436f756e742d30',
    ct: '1c5250d8034ec2b784ba2cfd69dbdb8af406cfe3ff938e131f0def8c8b60b4db21993c62ce81883d2dd1b51a28',
  },
  rfc9562AppendixA4: {
    source: 'RFC 9562 Appendix A.4 (UUIDv5, SHA-1, DNS namespace)',
    namespace: '6ba7b810-9dad-11d1-80b4-00c04fd430c8',
    name: 'www.example.com',
    uuid: '2ed6657d-e927-568b-95e1-2665a8aea6a2',
  },
} as const;

/** Fails unless the reference implementation reproduces every RFC anchor. */
export function verifyAnchors(spec: CryptoSpec): void {
  const failures: string[] = [];
  const expect = (name: string, actual: string, expected: string) => {
    if (actual !== expected) failures.push(`${name}: ${actual} != ${expected}`);
  };
  const h = ANCHORS.rfc5869TestCase1;
  expect('RFC 5869 PRK', hex(hkdfExtract(unhex(h.salt), unhex(h.ikm))), h.prk);
  expect('RFC 5869 OKM', hex(hkdf(unhex(h.salt), unhex(h.ikm), unhex(h.info), h.length)), h.okm);
  const x = ANCHORS.rfc7748Section61;
  expect('RFC 7748 Alice public', hex(x25519PublicKey(unhex(x.alicePrivate))), x.alicePublic);
  expect('RFC 7748 Bob public', hex(x25519PublicKey(unhex(x.bobPrivate))), x.bobPublic);
  expect('RFC 7748 shared (Alice)', hex(x25519(unhex(x.alicePrivate), unhex(x.bobPublic))), x.sharedSecret);
  expect('RFC 7748 shared (Bob)', hex(x25519(unhex(x.bobPrivate), unhex(x.alicePublic))), x.sharedSecret);
  const c = ANCHORS.rfc8439Section282;
  expect('RFC 8439 seal', hex(aeadSeal(unhex(c.key), unhex(c.nonce), unhex(c.aad), unhex(c.plaintext))), c.ciphertext + c.tag);
  expect('RFC 8439 open', hex(aeadOpen(unhex(c.key), unhex(c.nonce), unhex(c.aad), unhex(c.ciphertext + c.tag))), c.plaintext);
  const p = ANCHORS.rfc9180A21;
  const sealed = hpkeSealBase(spec, unhex(p.pkRm), unhex(p.ikmE), unhex(p.info), unhex(p.aad), unhex(p.pt));
  expect('RFC 9180 skEm', hex(sealed.skE), p.skEm);
  expect('RFC 9180 enc', hex(sealed.enc), p.enc);
  expect('RFC 9180 shared_secret', hex(sealed.sharedSecret), p.sharedSecret);
  expect('RFC 9180 key', hex(sealed.key), p.key);
  expect('RFC 9180 base_nonce', hex(sealed.baseNonce), p.baseNonce);
  expect('RFC 9180 ct', hex(sealed.ciphertext), p.ct);
  const u = ANCHORS.rfc9562AppendixA4;
  expect('RFC 9562 UUIDv5', uuidV5(u.namespace, u.name), u.uuid);
  if (failures.length > 0) {
    throw new Error(`The reference implementation does not reproduce the RFC anchors:\n${failures.join('\n')}`);
  }
}

const ascii = (text: string): Buffer => Buffer.from(text, 'utf8');

function varint(value: bigint): Buffer {
  const bytes: number[] = [];
  let rest = value;
  do {
    const low = Number(rest & 0x7fn);
    rest >>= 7n;
    bytes.push(rest === 0n ? low : low | 0x80);
  } while (rest !== 0n);
  return Buffer.from(bytes);
}

/** A Protobuf field key: the field number and its wire type (0 varint, 2 length-delimited). */
const key = (field: number, wireType: 0 | 2): Buffer => varint(BigInt((field << 3) | wireType));

/** A varint field; proto3 leaves a zero out unless the field tracks presence. */
function varintField(field: number, value: bigint, always = false): Buffer {
  return value === 0n && !always ? Buffer.alloc(0) : Buffer.concat([key(field, 0), varint(value)]);
}

/** A length-delimited field (bytes or an embedded message). */
function bytesField(field: number, value: Uint8Array, always = false): Buffer {
  return value.length === 0 && !always ? Buffer.alloc(0) : Buffer.concat([key(field, 2), varint(BigInt(value.length)), value]);
}

/** ZigZag, as `sint64` encodes a signed value. */
const zigzag = (value: bigint): bigint => BigInt.asUintN(64, (value << 1n) ^ (value >> 63n));

interface SeqRange {
  first: bigint;
  last: bigint;
}

/** `coldframe.device.v1.Downlink`, as Protobuf encodes it (fields in number order, no commands). */
function encodeDownlink(protocolVersion: number, ackedCounter: bigint, serverTimeMs: bigint, ackedReadings: SeqRange[] = []): Buffer {
  return Buffer.concat([
    varintField(1, BigInt(protocolVersion)),
    varintField(2, ackedCounter),
    varintField(3, serverTimeMs),
    ...ackedReadings.map(({ first, last }) => bytesField(5, Buffer.concat([varintField(1, first), varintField(2, last)]), true)),
  ]);
}

/** The Protobuf `Quantity` and `ChargeStatus` numbers of envelope.proto. */
const QUANTITY_NUMBERS = { soil_moisture: 1n, air_temperature: 2n, relative_humidity: 3n, gas_resistance: 4n } as const;
const CHARGE_NUMBERS = { unspecified: 0n, charging: 1n, not_charging: 2n } as const;

interface NodeReading {
  slot: number;
  readingSeq: bigint;
  quantity: keyof typeof QUANTITY_NUMBERS;
  value: bigint;
}

interface NodeFrameFields {
  protocolVersion: number;
  specHash: string;
  bootId: bigint;
  uptimeMs: bigint;
  measuredAtMs: bigint;
  reportSeq: bigint;
  readings: NodeReading[];
  batteryPercent: number;
  charging: keyof typeof CHARGE_NUMBERS;
}

/** `coldframe.device.v1.NodeFrame` with a synced time, as Protobuf encodes it (fields in number order). */
function encodeNodeFrame(frame: NodeFrameFields): Buffer {
  return Buffer.concat([
    varintField(1, BigInt(frame.protocolVersion)),
    bytesField(2, unhex(frame.specHash)),
    varintField(3, frame.bootId),
    varintField(4, frame.uptimeMs),
    varintField(5, BigInt.asUintN(64, frame.measuredAtMs), true),
    varintField(7, frame.reportSeq),
    ...frame.readings.map((reading) =>
      bytesField(
        8,
        Buffer.concat([
          varintField(1, BigInt(reading.slot)),
          varintField(2, reading.readingSeq),
          varintField(3, QUANTITY_NUMBERS[reading.quantity]),
          varintField(4, zigzag(reading.value)),
        ]),
        true,
      ),
    ),
    varintField(9, BigInt(frame.batteryPercent), true),
    varintField(10, CHARGE_NUMBERS[frame.charging]),
  ]);
}

/** The Node frame of the vectors: one wake with four Readings, a negative temperature among them. */
const NODE_FRAME: NodeFrameFields = {
  protocolVersion: 1,
  specHash: '',
  bootId: 3n,
  uptimeMs: 912345n,
  measuredAtMs: 1790000000000n,
  reportSeq: 104n,
  readings: [
    { slot: 0, readingSeq: 100n, quantity: 'soil_moisture', value: 1873n },
    { slot: 1, readingSeq: 101n, quantity: 'air_temperature', value: -2500n },
    { slot: 2, readingSeq: 102n, quantity: 'relative_humidity', value: 64250n },
    { slot: 3, readingSeq: 103n, quantity: 'gas_resistance', value: 48211n },
  ],
  batteryPercent: 87,
  charging: 'charging',
};

const NODE_FRAME_ACK = { ackedCounter: 42n, serverTimeMs: 1790000000321n, ackedReadings: [{ first: 100n, last: 104n }] };

const ROOT_A = '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f';
const ROOT_B = 'ffeeddccbbaa998877665544332211000f1e2d3c4b5a69788796a5b4c3d2e1f0';

/** Every vector, in the order vectors.json lists it. */
export function buildVectors(spec: CryptoSpec): Record<string, unknown> {
  verifyAnchors(spec);

  const keyHierarchy = [
    { name: 'counting root', rootKey: ROOT_A },
    { name: 'descending root', rootKey: ROOT_B },
  ].map(({ name, rootKey }) => {
    const keys = deriveDeviceKeys(spec, unhex(rootKey));
    return {
      name,
      rootKey,
      deviceKey: hex(keys.deviceKey),
      sealKey: hex(keys.sealKey),
      ackKey: hex(keys.ackKey),
      hubAuthKey: hex(keys.hubAuthKey),
      deviceId: hex(keys.deviceId),
    };
  });

  const frames = [
    { name: 'first uplink', rootKey: ROOT_A, purpose: 'seal', counter: 0n, plaintext: ascii('coldframe uplink frame') },
    { name: 'uplink with a 5-byte counter', rootKey: ROOT_A, purpose: 'seal', counter: 0x0100000005n, plaintext: ascii('reading 42') },
    { name: 'empty uplink', rootKey: ROOT_B, purpose: 'seal', counter: 18446744073709551614n, plaintext: Buffer.alloc(0) },
    {
      name: 'downlink acknowledging counter 1',
      rootKey: ROOT_A,
      purpose: 'ack',
      counter: 7n,
      plaintext: encodeDownlink(spec.protocolMajor, 1n, 1790000000000n),
    },
    {
      name: 'node frame with four readings',
      rootKey: ROOT_A,
      purpose: 'seal',
      counter: NODE_FRAME_ACK.ackedCounter,
      plaintext: encodeNodeFrame({ ...NODE_FRAME, protocolVersion: spec.protocolMajor }),
      message: {
        type: 'NodeFrame',
        protocolVersion: spec.protocolMajor,
        specHash: NODE_FRAME.specHash,
        bootId: NODE_FRAME.bootId.toString(),
        uptimeMs: NODE_FRAME.uptimeMs.toString(),
        measuredAtMs: NODE_FRAME.measuredAtMs.toString(),
        reportSeq: NODE_FRAME.reportSeq.toString(),
        readings: NODE_FRAME.readings.map(({ slot, readingSeq, quantity, value }) => ({
          slot,
          readingSeq: readingSeq.toString(),
          quantity,
          value: value.toString(),
        })),
        batteryPercent: NODE_FRAME.batteryPercent,
        charging: NODE_FRAME.charging,
      },
    },
    {
      name: 'downlink acknowledging the readings of the node frame',
      rootKey: ROOT_A,
      purpose: 'ack',
      counter: 8n,
      plaintext: encodeDownlink(spec.protocolMajor, NODE_FRAME_ACK.ackedCounter, NODE_FRAME_ACK.serverTimeMs, NODE_FRAME_ACK.ackedReadings),
      message: {
        type: 'Downlink',
        protocolVersion: spec.protocolMajor,
        ackedCounter: NODE_FRAME_ACK.ackedCounter.toString(),
        serverTimeMs: NODE_FRAME_ACK.serverTimeMs.toString(),
        ackedReadings: NODE_FRAME_ACK.ackedReadings.map(({ first, last }) => ({ first: first.toString(), last: last.toString() })),
      },
    },
  ].map(({ name, rootKey, purpose, counter, plaintext, message }) => {
    const keys = deriveDeviceKeys(spec, unhex(rootKey));
    const key = purpose === 'seal' ? keys.sealKey : keys.ackKey;
    const nonce = frameNonce(spec, keys.deviceId, counter);
    const aad = frameAad(spec, keys.deviceId, counter);
    return {
      name,
      rootKey,
      purpose,
      key: hex(key),
      deviceId: hex(keys.deviceId),
      counter: counter.toString(),
      plaintext: hex(plaintext),
      nonce: hex(nonce),
      aad: hex(aad),
      ciphertext: hex(aeadSeal(key, nonce, aad, plaintext)),
      // Only the frames whose plaintext is a Protobuf message of envelope.proto name its fields.
      ...(message === undefined ? {} : { message }),
    };
  });

  const replay = {
    name: 'accepts a counter above the high-water mark or unseen inside the window, once',
    window: spec.frame.replayWindow,
    steps: [
      ['100', true],
      ['100', false],
      ['101', true],
      ['99', true],
      ['99', false],
      ['38', true],
      ['37', false],
      ['200', true],
      ['101', false],
      ['150', true],
      ['150', false],
      ['137', true],
      ['136', false],
      ['201', true],
    ].map(([counter, accepted]) => ({ counter, accepted })),
  };

  const enrolment = [
    {
      name: 'hub enrolment',
      rootKey: ROOT_A,
      recipientPrivateKey: '5f3a1c2b7d9e8f60718293a4b5c6d7e8f90112233445566778899aabbccddeef', // gitleaks:allow (fixed test input)
      ikmE: 'a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0',
    },
    {
      name: 'second device, same server key',
      rootKey: ROOT_B,
      recipientPrivateKey: '5f3a1c2b7d9e8f60718293a4b5c6d7e8f90112233445566778899aabbccddeef', // gitleaks:allow (fixed test input)
      ikmE: '0f0e0d0c0b0a09080706050403020100ffeeddccbbaa99887766554433221100',
    },
  ].map(({ name, rootKey, recipientPrivateKey, ikmE }) => {
    const keys = deriveDeviceKeys(spec, unhex(rootKey));
    const recipientPublicKey = x25519PublicKey(unhex(recipientPrivateKey));
    const sealed = hpkeSealBase(spec, recipientPublicKey, unhex(ikmE), ascii(spec.enrolment.info), keys.deviceId, keys.deviceKey);
    return {
      name,
      rootKey,
      recipientPrivateKey,
      recipientPublicKey: hex(recipientPublicKey),
      fingerprint: fingerprint(recipientPublicKey),
      info: hex(ascii(spec.enrolment.info)),
      ikmE,
      ephemeralPrivateKey: hex(sealed.skE),
      deviceId: hex(keys.deviceId),
      deviceKey: hex(keys.deviceKey),
      enc: hex(sealed.enc),
      sharedSecret: hex(sealed.sharedSecret),
      key: hex(sealed.key),
      baseNonce: hex(sealed.baseNonce),
      ciphertext: hex(sealed.ciphertext),
    };
  });

  const setup = [
    {
      name: 'setup session with a lowercase code',
      popCode: 'k7m2q9xp',
      wrongPopCode: 'K7M2Q9XQ',
      appPrivateKey: '28c1d2e3f405162738495a6b7c8d9eafb0c1d2e3f405162738495a6b7c8d9e6f', // gitleaks:allow (fixed test input)
      hubPrivateKey: '9876543210fedcba9876543210fedcba0123456789abcdef0123456789abcd40', // gitleaks:allow (fixed test input)
      messages: [
        { direction: 'appToHub', counter: 0n, plaintext: ascii('identity please') },
        { direction: 'hubToApp', counter: 0n, plaintext: ascii('identity: hub') },
        { direction: 'appToHub', counter: 1n, plaintext: ascii('wifi scan please') },
      ],
    },
  ].map(({ name, popCode, wrongPopCode, appPrivateKey, hubPrivateKey, messages }) => {
    const appPublic = x25519PublicKey(unhex(appPrivateKey));
    const hubPublic = x25519PublicKey(unhex(hubPrivateKey));
    const app = setupKeys(spec, unhex(appPrivateKey), hubPublic, appPublic, hubPublic, popCode);
    const hub = setupKeys(spec, unhex(hubPrivateKey), appPublic, appPublic, hubPublic, popCode);
    if (!app.appToHubKey.equals(hub.appToHubKey) || !app.hubToAppKey.equals(hub.hubToAppKey)) {
      throw new Error('setup keys differ between app and Hub');
    }
    const aad = setupAad(spec);
    return {
      name,
      popCode,
      normalizedPopCode: popCode.toUpperCase(),
      wrongPopCode,
      appPrivateKey,
      appPublicKey: hex(appPublic),
      hubPrivateKey,
      hubPublicKey: hex(hubPublic),
      sharedSecret: hex(app.sharedSecret),
      appToHubKey: hex(app.appToHubKey),
      hubToAppKey: hex(app.hubToAppKey),
      aad: hex(aad),
      messages: messages.map(({ direction, counter, plaintext }) => {
        const key = direction === 'appToHub' ? app.appToHubKey : app.hubToAppKey;
        const nonce = setupNonce(spec, counter);
        return {
          direction,
          counter: counter.toString(),
          plaintext: hex(plaintext),
          nonce: hex(nonce),
          ciphertext: hex(aeadSeal(key, nonce, aad, plaintext)),
        };
      }),
    };
  });

  const heartbeat = [
    {
      name: 'heartbeat',
      rootKey: ROOT_A,
      method: 'POST',
      path: '/device/heartbeat',
      body: ascii('{"protocolVersion":1,"uptimeMs":61000}'),
      timestampMs: 1790000000000n,
      nonce: '00112233445566778899aabbccddeeff',
    },
    {
      name: 'empty body',
      rootKey: ROOT_B,
      method: 'POST',
      path: '/device/ingest',
      body: Buffer.alloc(0),
      timestampMs: 1790000123456n,
      nonce: 'f0e1d2c3b4a5968778695a4b3c2d1e0f',
    },
  ].map(({ name, rootKey, method, path, body, timestampMs, nonce }) => {
    const keys = deriveDeviceKeys(spec, unhex(rootKey));
    const canonical = heartbeatCanonical(spec, method, path, body, timestampMs, unhex(nonce));
    const signature = hex(hmacSha256(keys.hubAuthKey, ascii(canonical)));
    const { headers } = spec.heartbeat;
    return {
      name,
      rootKey,
      hubAuthKey: hex(keys.hubAuthKey),
      deviceId: hex(keys.deviceId),
      method,
      path,
      body: hex(body),
      timestampMs: timestampMs.toString(),
      nonce,
      bodyHash: hex(sha256(body)),
      canonical,
      signature,
      headers: {
        [headers.device]: hex(keys.deviceId),
        [headers.timestamp]: timestampMs.toString(),
        [headers.nonce]: nonce,
        [headers.signature]: signature,
      },
    };
  });

  const namespace = uuidV5(spec.sensorId.urlNamespace, spec.sensorId.namespaceName);
  if (namespace !== spec.sensorId.namespace) {
    throw new Error(`sensorId.namespace must be ${namespace}, the UUIDv5 of its namespaceName in the URL namespace`);
  }
  const sensorIds = [
    { name: 'soil moisture in slot 0', rootKey: ROOT_A, slot: 0, quantity: spec.sensorId.quantities.soilMoisture },
    { name: 'gas resistance in slot 3 of another device', rootKey: ROOT_B, slot: 3, quantity: spec.sensorId.quantities.gasResistance },
  ].map(({ name, rootKey, slot, quantity }) => {
    const keys = deriveDeviceKeys(spec, unhex(rootKey));
    return {
      name,
      rootKey,
      deviceId: hex(keys.deviceId),
      slot,
      quantity,
      namespace,
      uuidName: `${hex(keys.deviceId)}:${String(slot)}:${quantity}`,
      sensorId: sensorId(spec, keys.deviceId, slot, quantity),
    };
  });

  return {
    $comment: VECTORS_COMMENT,
    protocolMajor: spec.protocolMajor,
    keyHierarchy,
    frames,
    replay,
    enrolment,
    setup,
    heartbeat,
    sensorId: sensorIds,
    anchors: ANCHORS,
  };
}
