import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ktlint)
}

group = "com.escendit.coldframe"
version = "0.0.0"

// Tests live under tests/kt/, mirroring the module (see docs/quickstart.md).
val testRoot = rootDir.resolve("tests/kt/core")

kotlin {
    explicitApi()
    jvmToolchain(25)

    // The JVM target only runs commonTest and jvmTest under `check`; the apps use Android and iOS.
    jvm()

    android {
        namespace = "com.escendit.coldframe.core"
        compileSdk =
            libs.versions.android.compile.sdk
                .get()
                .toInt()
        minSdk =
            libs.versions.android.min.sdk
                .get()
                .toInt()
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    // On Linux the iOS klibs cross-compile; linking the framework needs a Mac and is skipped.
    val xcFramework = XCFramework("ColdframeCore")
    listOf(iosArm64(), iosSimulatorArm64()).forEach { target ->
        target.binaries.framework {
            baseName = "ColdframeCore"
            isStatic = true
            xcFramework.add(this)
        }
    }

    // The default hierarchy plus one intermediate source set shared by the JVM and Android.
    @OptIn(ExperimentalKotlinGradlePluginApi::class)
    applyDefaultHierarchyTemplate {
        common {
            group("jvmShared") {
                withJvm()
                withCompilations { it.platformType == KotlinPlatformType.androidJvm }
            }
        }
    }

    compilerOptions {
        optIn.add("org.publicvalue.multiplatform.oidc.ExperimentalOpenIdConnect")
    }

    sourceSets {
        // kotlinx-coroutines-test's virtual-time helpers are marked experimental.
        matching { it.name.endsWith("Test") }.configureEach {
            languageSettings.optIn("kotlinx.coroutines.ExperimentalCoroutinesApi")
        }

        commonMain {
            // CryptoSpec (labels, sizes, header names) is generated by packages/crypto-spec
            // (`pnpm --filter @coldframe/crypto-spec run generate`); Story 3.6 builds the crypto on it.
            kotlin.srcDir("generated/kotlin")
            dependencies {
                api(libs.kotlinx.coroutines.core)
                implementation(libs.oidc.core)
                implementation(libs.oidc.tokenstore)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.serialization.kotlinx.json)
                implementation(libs.kotlinx.serialization.json)
                api(libs.multiplatform.settings)
            }
        }

        // The JVM certificate classifier, shared by the JVM target (tests) and Android.
        named("jvmSharedMain") {
            kotlin.setSrcDirs(listOf("src/jvmShared/kotlin"))
        }
        jvmMain {
            dependencies {
                implementation(libs.ktor.client.okhttp)
            }
        }
        androidMain {
            dependencies {
                api(libs.oidc.appsupport)
                implementation(libs.activity)
                implementation(libs.ktor.client.okhttp)
            }
        }
        iosMain {
            dependencies {
                api(libs.oidc.appsupport)
                implementation(libs.ktor.client.darwin)
            }
        }

        commonTest {
            kotlin.setSrcDirs(listOf(testRoot.resolve("commonTest/kotlin")))
            resources.setSrcDirs(listOf(testRoot.resolve("commonTest/resources")))

            dependencies {
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.test)
                implementation(libs.ktor.client.mock)
                implementation(libs.multiplatform.settings.test)
            }
        }
        jvmTest {
            kotlin.setSrcDirs(listOf(testRoot.resolve("jvmTest/kotlin")))
            resources.setSrcDirs(listOf(testRoot.resolve("jvmTest/resources")))
        }
    }
}

ktlint {
    version.set(libs.versions.ktlint.cli)
}
