// Generated by packages/crypto-spec/scripts/generate.ts from crypto-spec.json. Do not edit.
// Regenerate with `pnpm --filter @coldframe/crypto-spec run generate`.

//! Constants of the Device crypto contract, `packages/crypto-spec/crypto-spec.json` (AD-12, AD-17,
//! AD-25).

// Protocol

/// The current wire major; every frame and envelope carries it.
pub const PROTOCOL_MAJOR: u8 = 1;

// Key hierarchy (AD-12)

/// Length of the eFuse root key in bytes.
pub const ROOT_KEY_LENGTH: usize = 32;

/// K_dev message: `K_dev = HMAC-SHA256(key = root, msg = label)`.
pub const DEVICE_KEY_LABEL: &str = "coldframe/device/v1";

/// Length of K_dev in bytes.
pub const DEVICE_KEY_LENGTH: usize = 32;

/// Length of a purpose key in bytes: `HKDF-SHA256(salt = empty, ikm = K_dev, info = label, L =
/// length)`.
pub const PURPOSE_KEY_LENGTH: usize = 32;

/// HKDF info of the uplink (frame) sealing key.
pub const SEAL_LABEL: &str = "seal/v1";

/// HKDF info of the downlink (acknowledgement) sealing key.
pub const ACK_LABEL: &str = "ack/v1";

/// HKDF info of the Hub request authentication key.
pub const HUB_AUTH_LABEL: &str = "hub-auth/v1";

/// HKDF info of the Device ID: `HKDF-SHA256(salt = empty, ikm = K_dev, info = label, L = length);
/// text form is lowercase hex`.
pub const DEVICE_ID_LABEL: &str = "device-id/v1";

/// Length of the Device ID in bytes.
pub const DEVICE_ID_LENGTH: usize = 8;

/// Length of the Device ID text form (lowercase hex).
pub const DEVICE_ID_HEX_LENGTH: usize = 16;

// AEAD (ChaCha20-Poly1305)

/// AEAD key length in bytes.
pub const AEAD_KEY_LENGTH: usize = 32;

/// AEAD nonce length in bytes.
pub const AEAD_NONCE_LENGTH: usize = 12;

/// AEAD tag length in bytes; a ciphertext is the encrypted bytes followed by the tag.
pub const AEAD_TAG_LENGTH: usize = 16;

// Frames and downlinks (AD-12, AD-17)

/// Device ID bytes at the start of the nonce: `device_id[0..4] || counter_u64_be`.
pub const FRAME_NONCE_DEVICE_ID_PREFIX_LENGTH: usize = 4;

/// Frame AAD length in bytes: `u8 protocol_major || device_id(8) || counter_u64_be`.
pub const FRAME_AAD_LENGTH: usize = 17;

/// Counters below the high-water mark that stay acceptable once each.
pub const REPLAY_WINDOW: usize = 64;

// Enrolment (HPKE, RFC 9180)

/// HPKE mode: base.
pub const HPKE_MODE: u8 = 0;

/// HPKE KEM: DHKEM(X25519, HKDF-SHA256).
pub const HPKE_KEM_ID: u16 = 32;

/// HPKE KDF: HKDF-SHA256.
pub const HPKE_KDF_ID: u16 = 1;

/// HPKE AEAD: ChaCha20Poly1305.
pub const HPKE_AEAD_ID: u16 = 3;

/// RFC 9180 labeled-KDF prefix.
pub const HPKE_VERSION_LABEL: &str = "HPKE-v1";

/// RFC 9180 DeriveKeyPair extract label.
pub const HPKE_LABEL_DKP_PRK: &str = "dkp_prk";

/// RFC 9180 DeriveKeyPair expand label.
pub const HPKE_LABEL_SK: &str = "sk";

/// RFC 9180 ExtractAndExpand extract label.
pub const HPKE_LABEL_EAE_PRK: &str = "eae_prk";

/// RFC 9180 ExtractAndExpand expand label.
pub const HPKE_LABEL_SHARED_SECRET: &str = "shared_secret";

/// RFC 9180 key schedule label.
pub const HPKE_LABEL_PSK_ID_HASH: &str = "psk_id_hash";

/// RFC 9180 key schedule label.
pub const HPKE_LABEL_INFO_HASH: &str = "info_hash";

/// RFC 9180 key schedule label.
pub const HPKE_LABEL_SECRET: &str = "secret";

/// RFC 9180 key schedule label.
pub const HPKE_LABEL_KEY: &str = "key";

/// RFC 9180 key schedule label.
pub const HPKE_LABEL_BASE_NONCE: &str = "base_nonce";

/// HPKE info of the enrolment: `RFC 9180 base mode, single-shot Seal at sequence 0: pt = K_dev, aad
/// = device_id`.
pub const ENROLMENT_INFO: &str = "coldframe/enrolment/v1";

/// Length of a raw X25519 public or private key in bytes.
pub const X25519_KEY_LENGTH: usize = 32;

/// Length of the HPKE encapsulated key in bytes.
pub const HPKE_ENC_LENGTH: usize = 32;

// BLE setup session (AD-25)

/// Setup-session HKDF info prefix: `okm = HKDF-SHA256(salt = UTF-8(uppercase PoP code), ikm =
/// X25519(own, peer), info = label || app_pub || hub_pub, L = okmLength)`.
pub const SETUP_LABEL: &str = "coldframe/setup/v1";

/// Setup-session HKDF output length in bytes.
pub const SETUP_OKM_LENGTH: usize = 64;

/// Length of each direction key in bytes.
pub const SETUP_KEY_LENGTH: usize = 32;

/// Longest PoP code accepted, in characters: the PoP code is ASCII, 1 to maxCodeLength characters;
/// it is uppercased (ASCII only) before use.
pub const SETUP_MAX_CODE_LENGTH: usize = 64;

/// Offset of the app-to-Hub key in the HKDF output.
pub const SETUP_APP_TO_HUB_KEY_OFFSET: usize = 0;

/// Offset of the Hub-to-app key in the HKDF output.
pub const SETUP_HUB_TO_APP_KEY_OFFSET: usize = 32;

/// Zero bytes at the start of the nonce: `0x00000000 || counter_u64_be, one counter per direction`.
pub const SETUP_NONCE_PREFIX_LENGTH: usize = 4;

/// Counter of the first message in each direction.
pub const SETUP_FIRST_COUNTER: u64 = 0;

// Heartbeat authentication (AD-12)

/// Separator of the canonical string: `METHOD \n PATH \n hex(SHA-256(body)) \n TIMESTAMP_MS \n
/// NONCE_HEX, lowercase hex, no trailing newline; METHOD is uppercase and PATH is the absolute
/// request path without query string, exactly as sent (for example /device/heartbeat)`.
pub const HEARTBEAT_SEPARATOR: &str = "\n";

/// Header carrying the Device ID (lowercase hex).
pub const HEARTBEAT_DEVICE_HEADER: &str = "X-Coldframe-Device";

/// Header carrying the request time in Unix milliseconds.
pub const HEARTBEAT_TIMESTAMP_HEADER: &str = "X-Coldframe-Timestamp";

/// Header carrying the request nonce (lowercase hex).
pub const HEARTBEAT_NONCE_HEADER: &str = "X-Coldframe-Nonce";

/// Header carrying the signature: `lowercase hex HMAC-SHA256(hub-auth key, canonical)`.
pub const HEARTBEAT_SIGNATURE_HEADER: &str = "X-Coldframe-Signature";

/// Length of the request nonce in bytes.
pub const HEARTBEAT_NONCE_LENGTH: usize = 16;

/// Largest accepted difference between the request time and the Server clock, in ms.
pub const HEARTBEAT_MAX_SKEW_MS: u64 = 300000;
