import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.ktlint)
}

group = "com.escendit.coldframe"
version = "0.0.0"

// Tests live under tests/kt/, mirroring the module (see docs/quickstart.md).
val testRoot = rootDir.resolve("tests/kt/design-tokens")

kotlin {
    explicitApi()
    jvmToolchain(25)

    // The JVM target runs the tests; the Android app depends on the Android target. iOS uses the
    // Swift tokens package (packages/swift/design-tokens), so there is no iOS target here.
    jvm()

    android {
        namespace = "com.escendit.coldframe.designtokens"
        compileSdk =
            libs.versions.android.compile.sdk
                .get()
                .toInt()
        minSdk =
            libs.versions.android.min.sdk
                .get()
                .toInt()
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    sourceSets {
        commonMain {
            // Colours, typography, spacing, radii and icons are generated by
            // packages/design-tokens (`pnpm --filter @coldframe/design-tokens run generate`).
            kotlin.srcDir("generated/kotlin")
        }
        commonTest {
            kotlin.setSrcDirs(listOf(testRoot.resolve("commonTest/kotlin")))
            resources.setSrcDirs(listOf(testRoot.resolve("commonTest/resources")))

            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}

ktlint {
    version.set(libs.versions.ktlint.cli)
}
