/**
 * Generates `src/schema.ts` from `packages/openapi/coldframe.openapi.json` with openapi-typescript.
 * Run `pnpm --filter @coldframe/api-client generate` after changing the contract; a test in
 * `tests/ts/api-client` fails while the committed schema is stale.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

export const contractPath = fileURLToPath(new URL('../../../openapi/coldframe.openapi.json', import.meta.url));
export const schemaPath = fileURLToPath(new URL('../src/schema.ts', import.meta.url));

const header = `/* eslint-disable -- generated code keeps openapi-typescript's own style */
/**
 * Generated by openapi-typescript from packages/openapi/coldframe.openapi.json.
 * Do not edit: run \`pnpm --filter @coldframe/api-client generate\`.
 */

`;

/** The schema module for the current contract, as text. */
export async function generateSchema(): Promise<string> {
  const contract: unknown = JSON.parse(readFileSync(contractPath, 'utf8'));
  const ast = await openapiTS(contract as Parameters<typeof openapiTS>[0], { exportType: true });
  return header + astToString(ast);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(schemaPath, await generateSchema());
  console.log(`Wrote ${schemaPath}`);
}
