/* eslint-disable -- generated code keeps openapi-typescript's own style */
/**
 * Generated by openapi-typescript from packages/openapi/coldframe.openapi.json.
 * Do not edit: run `pnpm --filter @coldframe/api-client generate`.
 */

export type paths = {
    "/device/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A Hub reports that it is alive
         * @description Authenticated as a Device (security scheme deviceHmac), never with a Keycloak token. The Server rejects a bad signature, a timestamp more than 300000 ms off its clock and a replayed nonce; a valid heartbeat updates the Device's last-seen time. The Hub adopts serverTime for its own timing only and never stamps data with it.
         */
        post: operations["deviceHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A Hub relays sealed Node frames (placeholder)
         * @description Placeholder until Epic 4 defines the envelope and the per-frame statuses (AD-9). Authenticated as a Device (security scheme deviceHmac).
         */
        post: operations["deviceIngest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrolment-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the Server's X25519 enrolment public key
         * @description The app shows the fingerprint and writes the key to the Device over BLE; the Device seals K_dev to it with HPKE (AD-12).
         */
        get: operations["getEnrolmentKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the Sites the caller holds a Membership on, with the caller's Role
         * @description Only Active Sites. Ordered by creation (oldest first, then by Site ID); clients show them in this order and never re-sort. An empty list means the caller has no Membership.
         */
        get: operations["listSites"];
        put?: never;
        /**
         * Create a Site with the caller as its Owner
         * @description Idempotent per caller and Idempotency-Key for 24 h: a retry returns the original result, and a key reused with a different name is refused.
         */
        post: operations["createSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{siteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a Site with the caller's Role */
        get: operations["getSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename a Site
         * @description Only an Owner. The Server sets the Keycloak Organization displayName first, then records the rename. Renaming to the current name changes nothing.
         */
        patch: operations["renameSite"];
        trace?: never;
    };
    "/sites/{siteId}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enrol a Device on the Site
         * @description The app relays the Device's sealed enrolment unread. The Server opens K_dev with its enrolment private key, using deviceId as the HPKE associated data, stores K_dev encrypted at rest and adds the Device to the Site's roster. A Node sent with lotId claims that Lot: a Lot holds one Node. Idempotent per caller and Idempotency-Key for 24 h; enrolling the same Device on the same Site (and Lot) again answers the same. The Idempotency-Key covers the Device's registration on the Site; lotId is checked against the Device on every request, and a refused claim persists nothing for the Device, so a retry with the same key may name another Lot. Leaving out lotId never unassigns a Node. Nothing is persisted for the Device on any error.
         */
        post: operations["enrolDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{siteId}/lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the Site's Lots
         * @description Only live Lots; removed Lots are absent. In the Server's order: status (needsWater, needsCalibration, unknown, ok, paused, noNode), then creation time, then Lot ID. Clients show them in this order and never re-sort.
         */
        get: operations["listLots"];
        put?: never;
        /**
         * Create a Lot on the Site
         * @description Idempotent per caller and Idempotency-Key for 24 h: a retry returns the original Lot, and a key reused with a different name is refused. Lot names need not be unique.
         */
        post: operations["createLot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{siteId}/lots/{lotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a Lot, including a removed one
         * @description A removed Lot stays resolvable and carries removed: true.
         */
        get: operations["getLot"];
        put?: never;
        post?: never;
        /**
         * Remove a Lot
         * @description Refused while a Node is assigned to the Lot. The Lot's ID and history stay resolvable. Removing a removed Lot changes nothing.
         */
        delete: operations["removeLot"];
        options?: never;
        head?: never;
        /** Rename a Lot */
        patch: operations["renameLot"];
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /**
         * @description A Role on one Site, ordered Owner > Administrator > Member.
         * @enum {string}
         */
        SiteRole: "Owner" | "Administrator" | "Member";
        CreateSiteRequest: {
            /** @description The Site name. Trimmed; 1 to 100 characters after trimming. */
            name: string;
        };
        Site: {
            /**
             * Format: uuid
             * @description The Site ID.
             */
            id: string;
            /** @description The Site name. */
            name: string;
            role: components["schemas"]["SiteRole"];
        };
        SiteList: {
            /** @description In the Server's order: creation time, then Site ID. */
            sites: components["schemas"]["Site"][];
        };
        RenameSiteRequest: {
            /** @description The Site name. Trimmed; 1 to 100 characters after trimming. */
            name: string;
        };
        /**
         * @description Computed by the Server (AD-14); clients never compute it.
         * @enum {string}
         */
        LotStatus: "needsWater" | "needsCalibration" | "unknown" | "ok" | "paused" | "noNode";
        Lot: {
            /**
             * Format: uuid
             * @description The Lot ID, a UUIDv7.
             */
            id: string;
            /** @description The Lot name. Not unique. */
            name: string;
            status: components["schemas"]["LotStatus"];
            /** @description Present and true only for a removed Lot. */
            removed?: boolean;
        };
        LotList: {
            /** @description In the Server's order: status, then creation time, then Lot ID. */
            lots: components["schemas"]["Lot"][];
        };
        CreateLotRequest: {
            /** @description The Lot name. Trimmed; 1 to 100 characters after trimming. */
            name: string;
        };
        RenameLotRequest: {
            /** @description The Lot name. Trimmed; 1 to 100 characters after trimming. */
            name: string;
        };
        /** @description The Device ID, derived from the Device's eFuse-bound identity: 16 lowercase hex digits. */
        DeviceId: string;
        /** @enum {string} */
        DeviceKind: "hub" | "node";
        /**
         * @example {
         *       "protocolVersion": 1
         *     }
         * @example {
         *       "protocolVersion": 1,
         *       "uptimeMs": 3600000
         *     }
         */
        HeartbeatRequest: {
            /** @description The Device's wire major. */
            protocolVersion: number;
            /** @description Milliseconds since the Device booted. */
            uptimeMs?: number;
        };
        /**
         * @example {
         *       "serverTime": "2026-09-29T12:34:56.789Z"
         *     }
         * @example {
         *       "serverTime": "2026-09-29T12:34:56Z"
         *     }
         */
        HeartbeatResponse: {
            /**
             * Format: date-time
             * @description The Server clock, ISO-8601 UTC with Z.
             */
            serverTime: string;
        };
        EnrolmentKey: {
            /** @description The raw 32-byte X25519 enrolment public key, base64url without padding. */
            publicKey: string;
            /** @description Lowercase hex SHA-256 of the raw public key. The app shows it to the user; the Device checks it against the key as an integrity check only, since it travels with the key. Authenticity comes from fetching this over TLS and the fingerprint the user sees. */
            fingerprint: string;
        };
        EnrolDeviceRequest: {
            deviceId: components["schemas"]["DeviceId"];
            kind: components["schemas"]["DeviceKind"];
            /** @description The HPKE encapsulated key (32 bytes), base64url without padding. */
            enc: string;
            /** @description K_dev sealed with HPKE (48 bytes), base64url without padding. */
            ciphertext: string;
            /**
             * Format: uuid
             * @description The Lot of the Site a Node is put in. Only for a Node; a Hub with a lotId is a validation error. A Lot holds one Node.
             */
            lotId?: string;
        };
        Device: {
            id: components["schemas"]["DeviceId"];
            kind: components["schemas"]["DeviceKind"];
            /**
             * Format: uuid
             * @description The Site the Device is enrolled on.
             */
            siteId: string;
            /**
             * Format: uuid
             * @description The Lot a Node is on; absent for a Hub and an unassigned Node.
             */
            lotId?: string;
        };
        /** @description RFC 9457 Problem Details. */
        ProblemDetails: {
            /** @description Stable: urn:coldframe:problem:<slug>. The set grows as operations are added, so it is an x-extensible-enum: a client handles a type it does not know by its status. */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
    };
    responses: {
        /** @description urn:coldframe:problem:validation, or urn:coldframe:problem:idempotency-key-missing when the Idempotency-Key header is absent or empty. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:unauthorized: no valid access token (missing, expired, wrong issuer or audience). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:forbidden: the Site exists, but the caller has no Role on it or a lower one than the operation's minimum. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:site-not-found: no Site has this ID. */
        SiteNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:lot-not-found: no Lot has this ID on this Site, or it was removed (for rename and remove of an unknown ID). urn:coldframe:problem:site-not-found when the Site does not exist. */
        LotNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:idempotency-key-reused: the key was used within 24 h for a request with a different body. Nothing was created. */
        IdempotencyKeyReused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:lot-claimed: a Node is assigned to the Lot. Nothing changed; move or unassign the Node first. */
        LotClaimed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:device-unauthorized: the Device authentication failed (unknown Device, bad signature, timestamp more than 300000 ms off, or a replayed nonce). */
        DeviceUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:site-not-found: no Site has this ID. urn:coldframe:problem:lot-not-found: the Site has no such Lot (unknown, removed, or of another Site); nothing was enrolled. */
        DeviceEnrolmentNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:device-on-another-site: the Device is already enrolled on another Site. urn:coldframe:problem:lot-claimed: this Lot already has a Node. urn:coldframe:problem:device-assigned: the Node is in another Lot already; move it instead. Nothing was enrolled or assigned. */
        DeviceEnrolmentConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:identity-provider-unavailable: Keycloak could not be reached. The request stays pending; retry with the same Idempotency-Key. */
        IdentityProviderUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description The Site ID, which is the Keycloak Organization ID. */
        SiteId: string;
        /** @description Chosen by the client per creation; kept 24 h after the request once the creation completes, and until it completes while it is still pending. 1 to 200 printable ASCII characters. */
        IdempotencyKey: string;
        /** @description The Lot ID, a UUIDv7. */
        LotId: string;
        /** @description The calling Device's ID, 16 lowercase hex digits. */
        DeviceIdHeader: components["schemas"]["DeviceId"];
        /** @description The request time, Unix milliseconds UTC; rejected when more than 300000 ms off the Server clock. */
        DeviceTimestampHeader: string;
        /** @description 16 random bytes as 32 lowercase hex digits; a replayed nonce is rejected. */
        DeviceNonceHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    deviceHeartbeat: {
        parameters: {
            query?: never;
            header: {
                /** @description The calling Device's ID, 16 lowercase hex digits. */
                "X-Coldframe-Device": components["parameters"]["DeviceIdHeader"];
                /** @description The request time, Unix milliseconds UTC; rejected when more than 300000 ms off the Server clock. */
                "X-Coldframe-Timestamp": components["parameters"]["DeviceTimestampHeader"];
                /** @description 16 random bytes as 32 lowercase hex digits; a replayed nonce is rejected. */
                "X-Coldframe-Nonce": components["parameters"]["DeviceNonceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description The heartbeat is recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["DeviceUnauthorized"];
        };
    };
    deviceIngest: {
        parameters: {
            query?: never;
            header: {
                /** @description The calling Device's ID, 16 lowercase hex digits. */
                "X-Coldframe-Device": components["parameters"]["DeviceIdHeader"];
                /** @description The request time, Unix milliseconds UTC; rejected when more than 300000 ms off the Server clock. */
                "X-Coldframe-Timestamp": components["parameters"]["DeviceTimestampHeader"];
                /** @description 16 random bytes as 32 lowercase hex digits; a replayed nonce is rejected. */
                "X-Coldframe-Nonce": components["parameters"]["DeviceNonceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description The frames are accepted for processing. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["DeviceUnauthorized"];
        };
    };
    getEnrolmentKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The enrolment key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrolmentKey"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's Sites. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSite: {
        parameters: {
            query?: never;
            header: {
                /** @description Chosen by the client per creation; kept 24 h after the request once the creation completes, and until it completes while it is still pending. 1 to 200 printable ASCII characters. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSiteRequest"];
            };
        };
        responses: {
            /** @description The Site exists and the caller is its Owner. */
            201: {
                headers: {
                    /** @description The Site, /sites/{siteId}. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["IdempotencyKeyReused"];
            503: components["responses"]["IdentityProviderUnavailable"];
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Site. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SiteNotFound"];
        };
    };
    renameSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameSiteRequest"];
            };
        };
        responses: {
            /** @description The renamed Site. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SiteNotFound"];
            503: components["responses"]["IdentityProviderUnavailable"];
        };
    };
    enrolDevice: {
        parameters: {
            query?: never;
            header: {
                /** @description Chosen by the client per creation; kept 24 h after the request once the creation completes, and until it completes while it is still pending. 1 to 200 printable ASCII characters. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrolDeviceRequest"];
            };
        };
        responses: {
            /** @description The Device is enrolled on the Site. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["DeviceEnrolmentNotFound"];
            409: components["responses"]["DeviceEnrolmentConflict"];
            422: components["responses"]["IdempotencyKeyReused"];
        };
    };
    listLots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Site's Lots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SiteNotFound"];
        };
    };
    createLot: {
        parameters: {
            query?: never;
            header: {
                /** @description Chosen by the client per creation; kept 24 h after the request once the creation completes, and until it completes while it is still pending. 1 to 200 printable ASCII characters. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLotRequest"];
            };
        };
        responses: {
            /** @description The Lot exists on the Site. */
            201: {
                headers: {
                    /** @description The Lot, /sites/{siteId}/lots/{lotId}. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lot"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SiteNotFound"];
            422: components["responses"]["IdempotencyKeyReused"];
        };
    };
    getLot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
                /** @description The Lot ID, a UUIDv7. */
                lotId: components["parameters"]["LotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Lot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lot"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["LotNotFound"];
        };
    };
    removeLot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
                /** @description The Lot ID, a UUIDv7. */
                lotId: components["parameters"]["LotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Lot is removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["LotNotFound"];
            409: components["responses"]["LotClaimed"];
        };
    };
    renameLot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
                /** @description The Lot ID, a UUIDv7. */
                lotId: components["parameters"]["LotId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameLotRequest"];
            };
        };
        responses: {
            /** @description The renamed Lot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lot"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["LotNotFound"];
        };
    };
}
