/* eslint-disable -- generated code keeps openapi-typescript's own style */
/**
 * Generated by openapi-typescript from packages/openapi/coldframe.openapi.json.
 * Do not edit: run `pnpm --filter @coldframe/api-client generate`.
 */

export type paths = {
    "/device/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A Hub reports that it is alive
         * @description Authenticated as a Device (security scheme deviceHmac), never with a Keycloak token. The Server rejects a bad signature, a timestamp more than 300000 ms off its clock and a replayed nonce; a valid heartbeat updates the Device's last-seen time. The Hub adopts serverTime for its own timing only and never stamps data with it.
         */
        post: operations["deviceHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A Hub relays sealed Node frames
         * @description Authenticated as a Device (security scheme deviceHmac): the signer must be an enrolled Hub, and any enrolled Hub may relay any Node (AD-18). The body is at most 16384 bytes and carries at most 32 frames. The Hub relays frames and downlinks as opaque bytes and holds no Readings (AD-9). The Server answers 200 whenever the envelope parses, with one result per frame in request order; frames of one Node are processed in that order. A frame is acknowledged only after its Readings are durably stored: only stored and duplicate carry a sealed downlink, which the Hub passes to the Node unchanged. The Hub never treats a status as an acknowledgement and never synthesizes one. A Node deletes a buffered Reading only when an authentic downlink acknowledges its reading_seq: no status, retry and rejected_replay included, lets it drop one. Every resend is sealed again under a new counter; the same sealed bytes sent twice are rejected_replay.
         */
        post: operations["deviceIngest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrolment-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the Server's X25519 enrolment public key
         * @description The app shows the fingerprint and writes the key to the Device over BLE; the Device seals K_dev to it with HPKE (AD-12).
         */
        get: operations["getEnrolmentKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the Sites the caller holds a Membership on, with the caller's Role
         * @description Only Active Sites. Ordered by creation (oldest first, then by Site ID); clients show them in this order and never re-sort. An empty list means the caller has no Membership.
         */
        get: operations["listSites"];
        put?: never;
        /**
         * Create a Site with the caller as its Owner
         * @description Idempotent per caller and Idempotency-Key for 24 h: a retry returns the original result, and a key reused with a different name is refused.
         */
        post: operations["createSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{siteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a Site with the caller's Role */
        get: operations["getSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename a Site
         * @description Only an Owner. The Server sets the Keycloak Organization displayName first, then records the rename. Renaming to the current name changes nothing.
         */
        patch: operations["renameSite"];
        trace?: never;
    };
    "/sites/{siteId}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the Site's Devices
         * @description Every Device enrolled on the Site, Hubs and Nodes, Hubs by Device ID first, then Nodes by Lot name (unassigned last) then Device ID, from the devices projection of the Device streams. lastSeenAt is the time of the last accepted heartbeat. online is computed by the Server when it answers: for a Hub, true only while lastSeenAt is at most 120 s old (two missed 60 s heartbeats); the same window is applied to a Node until Nodes get their own rule, so a Node's online is not meaningful yet. It is never stored; clients show it as received and never compute or keep it.
         */
        get: operations["listDevices"];
        put?: never;
        /**
         * Enrol a Device on the Site
         * @description The app relays the Device's sealed enrolment unread. The Server opens K_dev with its enrolment private key, using deviceId as the HPKE associated data, stores K_dev encrypted at rest and adds the Device to the Site's roster. A Node sent with lotId claims that Lot: a Lot holds one Node. Idempotent per caller and Idempotency-Key for 24 h; enrolling the same Device on the same Site (and Lot) again answers the same. The Idempotency-Key covers the Device's registration on the Site; lotId is checked against the Device on every request, and a refused claim persists nothing for the Device, so a retry with the same key may name another Lot. Leaving out lotId never unassigns a Node. Nothing is persisted for the Device on any error.
         */
        post: operations["enrolDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{siteId}/devices/{deviceId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move a Node to another Lot
         * @description Administrator or Owner only; no Bluetooth is involved. The Device grain claims the target Lot first (a Lot holds one Node), then journals the move, and only then releases the Node's old Lot; that release is retried from persisted state until it succeeds, so the old Lot may show its Node for a moment after the answer. A refusal changes nothing. Moving a Node to the Lot it is on answers 200 and changes nothing; a Node on no Lot is put in the Lot. The Node's Reading history stays with the Node.
         */
        post: operations["moveDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{siteId}/devices/{deviceId}/unassign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unassign a Node from its Lot
         * @description Administrator or Owner only; no Bluetooth is involved. The Device grain journals the unassignment, then releases the Lot; that release is retried from persisted state until it succeeds. Later Readings of the Node are stored but not evaluated. Unassigning a Node that is on no Lot answers 200 and changes nothing. Readings are never deleted.
         */
        post: operations["unassignDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{siteId}/sensors/{sensorId}/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a Sensor's Calibration state and recent Readings
         * @description Administrator or Owner only (Story 5.2). Where the Sensor's Calibration stands: the Calibration in force and a point the Server kept while its partner is missing, so a Calibrate flow left after the dry point resumes at the wet one. readings lists the Sensor's recent stored Readings, newest first, each with the reading_seq the POST names; it is empty for a Sensor whose Specification has no Calibration. Clients re-read it while a Calibrate flow waits for a fresh Reading.
         */
        get: operations["getSensorCalibration"];
        put?: never;
        /**
         * Calibrate a Sensor
         * @description Administrator or Owner only; the reference points are chosen from Readings the Server already stored, never over Bluetooth. The body names a dry point (the probe in dry soil) and/or a wet point (in water), each by the reading_seq of a stored Reading of the Sensor; the Server reads the raw value from that Reading. Only a Sensor whose Specification calls for Calibration (calibration: true) can be calibrated. One point is kept until the other one arrives, in either order, and the Sensor stays as calibrated as it was. Two points that are distinct (their raw values at least 16 counts apart, in either orientation) save a Calibration with a new ID: it is two-point linear, a Reading's percentage is clamped to 0 to 100 and rounded to the nearest 5, and it applies to Readings stored from then on (stored Readings keep the Calibration they were stored with; Threshold percentages do not change). The Sensor grain journals the Calibration and sets it in force on the Node before this answers 200; when that fails the Calibration stays saved, the Server delivers it again until the Node's Device grain holds it, and the answer is 503 calibration-not-delivered. The Lot leaves needs-calibration once the Calibration is saved; its percentage appears with the next stored Reading. Sending the pair that is already in force again changes nothing. A refusal changes nothing.
         */
        post: operations["calibrateSensor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{siteId}/sensors/{sensorId}/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a Sensor's Thresholds
         * @description Member and up (Story 5.3): every Member reads, only an Administrator or Owner changes them. Each side is default (it follows the Specification's default, which may be absent), override (its own value) or cleared (no Threshold). value is the effective Threshold in the display unit (a calibrating Sensor: whole percent 0 to 100, whatever its Calibration; temperature in °C, humidity in %, gas resistance in kΩ) and is omitted when the side has none. A Sensor alerts exactly when its effective low exists. proposedLow is Min + 20 % x (Max - Min) of the Sensor's range (20 for a calibrating Sensor) when its Specification has no default low; there is never a proposed high. It is a suggestion and is not stored until an Administrator saves it as an override. A Sensor of another Site is not disclosed.
         */
        get: operations["getSensorThresholds"];
        /**
         * Set a Sensor's Thresholds
         * @description Administrator or Owner only (Story 5.3); a Member gets 403. The Sensor grain is the only validator. A side that is absent stays as it is. On the effective values after the change: a high needs a low (low is required on an alerting Sensor), the low must be strictly below the high, an empty high is allowed and never alerts, and clearing both sides makes the Sensor watched only. A side is default, override with a value, or cleared; a value on default or cleared, or none on override, is refused. A calibrating Sensor takes whole percent 0 to 100, any other Sensor a value within its Specification's range, in the display unit (°C, %, kΩ). A change is saved and answers 200 with the Thresholds in force; a request that leaves both sides as they are answers 200 and saves nothing. A saved change starts a new evaluation epoch for Threshold Alerts. A refusal changes nothing. A later Specification declaration never replaces an override.
         */
        put: operations["setSensorThresholds"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{siteId}/lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the Site's Lots
         * @description Only live Lots; removed Lots are absent. In the Server's order: status (needsWater, needsCalibration, unknown, ok, paused, noNode), then creation time, then Lot ID. Clients show them in this order and never re-sort.
         */
        get: operations["listLots"];
        put?: never;
        /**
         * Create a Lot on the Site
         * @description Idempotent per caller and Idempotency-Key for 24 h: a retry returns the original Lot, and a key reused with a different name is refused. Lot names need not be unique.
         */
        post: operations["createLot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{siteId}/lots/{lotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a Lot, including a removed one
         * @description A removed Lot stays resolvable and carries removed: true.
         */
        get: operations["getLot"];
        put?: never;
        post?: never;
        /**
         * Remove a Lot
         * @description Refused while a Node is assigned to the Lot. The Lot's ID and history stay resolvable. Removing a removed Lot changes nothing.
         */
        delete: operations["removeLot"];
        options?: never;
        head?: never;
        /** Rename a Lot */
        patch: operations["renameLot"];
        trace?: never;
    };
    "/sites/{siteId}/lots/{lotId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a Lot's daily history of one quantity
         * @description One entry per UTC day that has Readings, ascending, with the day's lowest and highest converted value and its Reading count; a day without Readings is absent, never zero. The history follows the Lot's current Node: only the Readings of that Node since it was put in the Lot. Values are converted by the Server like Lot.sensors. from defaults to to minus 30 days and to to now. The page holds at most limit days (default 31, at most 366); nextCursor, when present, is passed unchanged as cursor to read the next page. A bad quantity, from, to, cursor or limit, or from after to, answers 400 validation.
         */
        get: operations["getLotHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /**
         * @description A Role on one Site, ordered Owner > Administrator > Member.
         * @enum {string}
         */
        SiteRole: "Owner" | "Administrator" | "Member";
        CreateSiteRequest: {
            /** @description The Site name. Trimmed; 1 to 100 characters after trimming. */
            name: string;
        };
        Site: {
            /**
             * Format: uuid
             * @description The Site ID.
             */
            id: string;
            /** @description The Site name. */
            name: string;
            role: components["schemas"]["SiteRole"];
        };
        SiteList: {
            /** @description In the Server's order: creation time, then Site ID. */
            sites: components["schemas"]["Site"][];
        };
        RenameSiteRequest: {
            /** @description The Site name. Trimmed; 1 to 100 characters after trimming. */
            name: string;
        };
        /**
         * @description Computed by the Server (AD-14); clients never compute it.
         * @enum {string}
         */
        LotStatus: "needsWater" | "needsCalibration" | "unknown" | "ok" | "paused" | "noNode";
        /**
         * @description Why an unknown Lot cannot be read (AD-14): its Node is silent, or the Hub that relays it is.
         * @enum {string}
         */
        LotUnknownCause: "node" | "hub";
        /**
         * @description Where a Pause of the Lot's Node comes from (AD-8).
         * @enum {string}
         */
        LotPauseSource: "device" | "site";
        /**
         * @description A Lot with its Server-computed status (AD-14). Clients render these fields and never derive them.
         * @example {
         *       "id": "0192f3a4-8a00-7c3d-8e4f-5a6b7c8d9e02",
         *       "name": "Potatoes",
         *       "status": "noNode",
         *       "statusSince": "2026-10-06T07:02:00.000Z"
         *     }
         * @example {
         *       "id": "0192f3a4-8a00-7c3d-8e4f-5a6b7c8d9e03",
         *       "name": "Peppers",
         *       "status": "needsCalibration",
         *       "statusSince": "2026-10-06T07:02:00.000Z",
         *       "lastReadingAt": "2026-10-06T07:17:00.000Z"
         *     }
         * @example {
         *       "id": "0192f3a4-8a00-7c3d-8e4f-5a6b7c8d9e04",
         *       "name": "Beans",
         *       "status": "unknown",
         *       "statusSince": "2026-10-06T01:05:00.000Z",
         *       "unknownCause": "node"
         *     }
         * @example {
         *       "id": "0192f3a4-8a00-7c3d-8e4f-5a6b7c8d9e05",
         *       "name": "Strawberries",
         *       "status": "paused",
         *       "statusSince": "2026-10-01T09:00:00.000Z",
         *       "pausedBy": [
         *         "device",
         *         "site"
         *       ],
         *       "pausedUntil": "2026-11-01T00:00:00.000Z"
         *     }
         */
        Lot: {
            /**
             * Format: uuid
             * @description The Lot ID, a UUIDv7.
             */
            id: string;
            /** @description The Lot name. Not unique. */
            name: string;
            status: components["schemas"]["LotStatus"];
            /**
             * Format: date-time
             * @description When the Lot got its current status, ISO-8601 UTC with Z. It does not move while the status stays the same.
             */
            statusSince: string;
            /**
             * Format: date-time
             * @description The newest measured_at of the Readings of the Lot's Node since it was put in the Lot, ISO-8601 UTC with Z; absent without a Node or before its first Reading.
             */
            lastReadingAt?: string;
            /** @description Present only when status is unknown. */
            unknownCause?: components["schemas"]["LotUnknownCause"];
            /** @description The Pause sources of the Lot's Node, device before site. Present and non-empty only when status is paused. */
            pausedBy?: components["schemas"]["LotPauseSource"][];
            /**
             * Format: date-time
             * @description When the Pause ends, ISO-8601 UTC with Z: the latest end of its sources. Absent when status is not paused or any source has no end.
             */
            pausedUntil?: string;
            /** @description The calibrated soil moisture of the Lot's newest Reading, in percent. Absent without a Calibration; the Server sends it from Epic 5 on. */
            moisturePercent?: number;
            /** @description The low Threshold of the Lot's soil-moisture Sensor, in percent. Absent without one; the Server sends it from Epic 6 on. */
            lowThresholdPercent?: number;
            /** @description The Lot's Node with its battery and last seen. Sent only by GET /sites/{siteId}/lots/{lotId}, never by the list, and only while the Lot holds a Node. */
            node?: components["schemas"]["NodeStatus"];
            /** @description The newest Reading of each Sensor of the Lot's Node, converted by the Server, in slot order. Sent with node, only by GET /sites/{siteId}/lots/{lotId}; empty while the Node has no Reading. */
            sensors?: components["schemas"]["SensorReading"][];
            /** @description Present and true only for a removed Lot. */
            removed?: boolean;
        };
        /**
         * @description What a Sensor measures.
         * @enum {string}
         */
        SensorQuantity: "soil_moisture" | "air_temperature" | "relative_humidity" | "gas_resistance";
        /**
         * @description The unit of a converted value: raw is the uncalibrated soil-moisture count; a soil-moisture Reading stored under a Calibration (Epic 5) is a percentage, rounded to the nearest 5.
         * @enum {string}
         */
        SensorUnit: "raw" | "°C" | "%" | "kΩ";
        /**
         * @description The charger state of a Node at its last report.
         * @enum {string}
         */
        ChargeState: "charging" | "notCharging";
        /** @description A Node's health from its newest device report. */
        NodeStatus: {
            deviceId: components["schemas"]["DeviceId"];
            /** @description The approximate battery charge of the newest report; absent when unknown. */
            batteryPercent?: number;
            /** @description Absent when the charger state is unknown or there is no report. */
            charging?: components["schemas"]["ChargeState"];
            /**
             * Format: date-time
             * @description The measured_at of the Node's newest device report, ISO-8601 UTC with Z; absent without a report.
             */
            lastSeenAt?: string;
        };
        /** @description The newest Reading of one Sensor, converted by the Server: soil moisture is the raw count, or a percentage rounded to the nearest 5 when the Reading was stored under a Calibration, temperature is in °C, humidity in %, gas resistance in kΩ. Clients only format it. */
        SensorReading: {
            quantity: components["schemas"]["SensorQuantity"];
            value: number;
            unit: components["schemas"]["SensorUnit"];
            /**
             * Format: date-time
             * @description When the Reading was taken, ISO-8601 UTC with Z.
             */
            measuredAt: string;
            /**
             * Format: uuid
             * @description The Sensor ID; names the Sensor in /sites/{siteId}/sensors/{sensorId}/calibration.
             */
            sensorId?: string;
            /** @description Whether the Sensor's Specification calls for Calibration (calibration: true). Clients show Calibrate only for such a Sensor, and only to an Administrator or Owner. */
            calibratable?: boolean;
        };
        LotHistoryDay: {
            /**
             * Format: date
             * @description A UTC date, yyyy-MM-dd.
             */
            day: string;
            /** @description The day's lowest converted value. */
            low: number;
            /** @description The day's highest converted value. */
            high: number;
            /** @description How many Readings the day has. */
            readingCount: number;
        };
        /**
         * @example {
         *       "quantity": "soil_moisture",
         *       "unit": "raw",
         *       "days": [
         *         {
         *           "day": "2026-10-05",
         *           "low": 1840,
         *           "high": 2210,
         *           "readingCount": 96
         *         },
         *         {
         *           "day": "2026-10-06",
         *           "low": 1790,
         *           "high": 2050,
         *           "readingCount": 30
         *         }
         *       ]
         *     }
         */
        LotHistory: {
            quantity: components["schemas"]["SensorQuantity"];
            unit: components["schemas"]["SensorUnit"];
            /** @description Days with Readings, ascending; a day without Readings is absent. */
            days: components["schemas"]["LotHistoryDay"][];
            /** @description Opaque; present only when more days follow. */
            nextCursor?: string;
        };
        LotList: {
            /** @description In the Server's order: status, then creation time, then Lot ID. */
            lots: components["schemas"]["Lot"][];
        };
        CreateLotRequest: {
            /** @description The Lot name. Trimmed; 1 to 100 characters after trimming. */
            name: string;
        };
        RenameLotRequest: {
            /** @description The Lot name. Trimmed; 1 to 100 characters after trimming. */
            name: string;
        };
        /** @description The Device ID, derived from the Device's eFuse-bound identity: 16 lowercase hex digits. */
        DeviceId: string;
        /** @enum {string} */
        DeviceKind: "hub" | "node";
        /**
         * @example {
         *       "protocolVersion": 1
         *     }
         * @example {
         *       "protocolVersion": 1,
         *       "uptimeMs": 3600000
         *     }
         */
        HeartbeatRequest: {
            /** @description The Device's wire major. */
            protocolVersion: number;
            /** @description Milliseconds since the Device booted. */
            uptimeMs?: number;
        };
        /**
         * @example {
         *       "serverTime": "2026-09-29T12:34:56.789Z"
         *     }
         * @example {
         *       "serverTime": "2026-09-29T12:34:56Z"
         *     }
         */
        HeartbeatResponse: {
            /**
             * Format: date-time
             * @description The Server clock, ISO-8601 UTC with Z.
             */
            serverTime: string;
        };
        /** @description A serialized coldframe.device.v1.SealedEnvelope (packages/proto) in standard base64 with padding (RFC 4648 section 4). Opaque to the Hub in both directions. */
        SealedFrame: string;
        /**
         * @example {
         *       "frames": []
         *     }
         * @example {
         *       "frames": [
         *         "CAESCJIGRCLAEvSBGCoiUZUKap6tCEOuyAMzBFCKubljcaiXOauv8QrS8pkfNG/VkADvmH7a4XwAgs52rxPmwF9aIYr/fy86/UoRx9oyIul7C8+hhwoc4E8slPrfllzdew=="
         *       ]
         *     }
         */
        IngestRequest: {
            /** @description The sealed Node frames, in the order the Hub received them. */
            frames: components["schemas"]["SealedFrame"][];
        };
        /**
         * @description stored: at least one Reading or the device report of the frame was new and is committed. duplicate: everything in the frame was stored before; it is acknowledged again. rejected_auth: the frame is not a SealedEnvelope of a supported protocol_version, does not open with the Node's seal/v1 key, or its plaintext is not a valid Node frame. rejected_replay: the frame's counter is below the Node's 64-entry replay window or was seen, as when the same sealed bytes arrive twice or after a database restore; the Node keeps its Readings and resends them freshly sealed under a higher counter. rejected_time: a synced measured_at is more than 5 min after the Server clock. unknown_device: the Device ID is not an enrolled Node. retry: the Server could not finish the frame and does not acknowledge it; the Node keeps its Readings and resends them, freshly sealed under a new counter (the same sealed bytes may be rejected_replay).
         * @enum {string}
         */
        IngestFrameStatus: "stored" | "duplicate" | "rejected_auth" | "rejected_replay" | "rejected_time" | "unknown_device" | "retry";
        /**
         * @example {
         *       "status": "stored",
         *       "downlink": "CAESCJIGRCLAEvSBGAgiIdrMC2wKZAR61wCrDAsa60T87aCO494L/YK5BuXZVqUX7Q=="
         *     }
         * @example {
         *       "status": "rejected_auth"
         *     }
         */
        IngestFrameResult: {
            status: components["schemas"]["IngestFrameStatus"];
            /** @description The sealed acknowledgement for the Node, sealed with its ack/v1 key; present exactly when status is stored or duplicate. */
            downlink?: components["schemas"]["SealedFrame"];
        };
        /**
         * @example {
         *       "results": []
         *     }
         * @example {
         *       "results": [
         *         {
         *           "status": "stored",
         *           "downlink": "CAESCJIGRCLAEvSBGAgiIdrMC2wKZAR61wCrDAsa60T87aCO494L/YK5BuXZVqUX7Q=="
         *         },
         *         {
         *           "status": "rejected_auth"
         *         }
         *       ]
         *     }
         * @example {
         *       "results": [
         *         {
         *           "status": "stored",
         *           "downlink": "CAESCJIGRCLAEvSBGAgiIdrMC2wKZAR61wCrDAsa60T87aCO494L/YK5BuXZVqUX7Q=="
         *         },
         *         {
         *           "status": "duplicate",
         *           "downlink": "CAESCJIGRCLAEvSBGAgiIdrMC2wKZAR61wCrDAsa60T87aCO494L/YK5BuXZVqUX7Q=="
         *         },
         *         {
         *           "status": "rejected_auth"
         *         },
         *         {
         *           "status": "rejected_replay"
         *         },
         *         {
         *           "status": "rejected_time"
         *         },
         *         {
         *           "status": "unknown_device"
         *         },
         *         {
         *           "status": "retry"
         *         }
         *       ]
         *     }
         */
        IngestResponse: {
            /** @description One result per frame of the request, in request order. */
            results: components["schemas"]["IngestFrameResult"][];
        };
        EnrolmentKey: {
            /** @description The raw 32-byte X25519 enrolment public key, base64url without padding. */
            publicKey: string;
            /** @description Lowercase hex SHA-256 of the raw public key. The app shows it to the user; the Device checks it against the key as an integrity check only, since it travels with the key. Authenticity comes from fetching this over TLS and the fingerprint the user sees. */
            fingerprint: string;
        };
        CalibrationPoint: {
            /**
             * Format: uint64
             * @description The reading_seq of a Reading the Server stored for this Sensor. The point's raw value is that Reading's.
             */
            readingSeq: number;
        };
        CalibrateSensorRequest: {
            dry?: components["schemas"]["CalibrationPoint"];
            wet?: components["schemas"]["CalibrationPoint"];
        };
        CalibrationValue: {
            /**
             * Format: int64
             * @description The raw value of the stored Reading the point was taken from.
             */
            rawValue: number;
        };
        /** @description Where a Sensor's Calibration stands. dry and wet are the points of the Calibration in force; pendingDry and pendingWet are a point kept while its partner is missing (also while a Sensor in force is being recalibrated). */
        Calibration: {
            /** @description Whether a Calibration is in force. */
            calibrated: boolean;
            /**
             * Format: uuid
             * @description The ID of the Calibration in force, stamped on every Reading stored under it; absent while uncalibrated.
             */
            calibrationId?: string;
            dry?: components["schemas"]["CalibrationValue"];
            wet?: components["schemas"]["CalibrationValue"];
            pendingDry?: components["schemas"]["CalibrationValue"];
            pendingWet?: components["schemas"]["CalibrationValue"];
        };
        /** @description One recent stored Reading of a Sensor a Calibration point can be taken from. */
        CalibrationReading: {
            /**
             * Format: uint64
             * @description The reading_seq the Calibration request names.
             */
            readingSeq: number;
            /**
             * Format: int64
             * @description The stored raw value.
             */
            rawValue: number;
            /**
             * Format: date-time
             * @description When the Reading was taken, ISO-8601 UTC with Z.
             */
            measuredAt: string;
        };
        /** @description Where a Sensor's Calibration stands, as the Calibration endpoint's 200 carries it, plus the recent stored Readings to pick a point from. */
        CalibrationState: {
            /** @description Whether a Calibration is in force. */
            calibrated: boolean;
            /**
             * Format: uuid
             * @description The ID of the Calibration in force; absent while uncalibrated.
             */
            calibrationId?: string;
            dry?: components["schemas"]["CalibrationValue"];
            wet?: components["schemas"]["CalibrationValue"];
            pendingDry?: components["schemas"]["CalibrationValue"];
            pendingWet?: components["schemas"]["CalibrationValue"];
            /** @description The recent stored Readings, newest first. */
            readings: components["schemas"]["CalibrationReading"][];
        };
        /**
         * @description How one side of a Sensor's Thresholds is set: default follows the Specification's default (which may be absent), override has its own value, cleared has no Threshold.
         * @enum {string}
         */
        ThresholdKind: "default" | "override" | "cleared";
        ThresholdSideRequest: {
            kind: components["schemas"]["ThresholdKind"];
            /** @description The Threshold in the display unit; required with override, refused with default and cleared. A calibrating Sensor: a whole percent from 0 to 100. */
            value?: number;
        };
        SetSensorThresholdsRequest: {
            low?: components["schemas"]["ThresholdSideRequest"];
            high?: components["schemas"]["ThresholdSideRequest"];
        };
        ThresholdSide: {
            kind: components["schemas"]["ThresholdKind"];
            /** @description The effective Threshold in the display unit; absent when the side has none. */
            value?: number;
        };
        /** @description A Sensor's Thresholds in force. A Sensor alerts exactly when its effective low exists. */
        SensorThresholds: {
            /**
             * @description The display unit of every value; % for a calibrating Sensor.
             * @enum {string}
             */
            unit: "%" | "°C" | "kΩ" | "raw";
            low: components["schemas"]["ThresholdSide"];
            high: components["schemas"]["ThresholdSide"];
            /** @description Min + 20 % x (Max - Min) of the Sensor's range (20 for a calibrating Sensor), present only when the Specification has no default low. There is no proposed high. */
            proposedLow?: number;
        };
        MoveDeviceRequest: {
            /**
             * Format: uuid
             * @description The Lot of the Site to move the Node to. A Lot that holds another Node answers 409 lot-claimed.
             */
            lotId: string;
        };
        EnrolDeviceRequest: {
            deviceId: components["schemas"]["DeviceId"];
            kind: components["schemas"]["DeviceKind"];
            /** @description The HPKE encapsulated key (32 bytes), base64url without padding. */
            enc: string;
            /** @description K_dev sealed with HPKE (48 bytes), base64url without padding. */
            ciphertext: string;
            /**
             * Format: uuid
             * @description The Lot of the Site a Node is put in. Only for a Node; a Hub with a lotId is a validation error. A Lot holds one Node.
             */
            lotId?: string;
        };
        Device: {
            id: components["schemas"]["DeviceId"];
            kind: components["schemas"]["DeviceKind"];
            /**
             * Format: uuid
             * @description The Site the Device is enrolled on.
             */
            siteId: string;
            /**
             * Format: uuid
             * @description The Lot a Node is on; absent for a Hub and an unassigned Node.
             */
            lotId?: string;
        };
        /**
         * @description A Device in the Site's Devices list.
         * @example {
         *       "id": "3f2a9c0d1e4b5a67",
         *       "kind": "hub",
         *       "lastSeenAt": "2026-10-06T07:02:00.000Z",
         *       "online": true
         *     }
         * @example {
         *       "id": "3f2a9c0d1e4b5a67",
         *       "kind": "hub",
         *       "online": false
         *     }
         */
        DeviceListItem: {
            id: components["schemas"]["DeviceId"];
            kind: components["schemas"]["DeviceKind"];
            /**
             * Format: uuid
             * @description The Lot a Node is on; absent for a Hub and an unassigned Node.
             */
            lotId?: string;
            /**
             * Format: date-time
             * @description For a Hub, when the Server accepted its last heartbeat; for a Node, the measured_at of its newest device report. ISO-8601 UTC with Z; absent until the first one.
             */
            lastSeenAt?: string;
            /** @description Computed by the Server at read time. For a Hub: lastSeenAt is present and at most 120 s old. Not meaningful for a Node yet. Clients never compute it. */
            online: boolean;
            /** @description The name of the Lot a Node is on; absent for a Hub and an unassigned Node. */
            lotName?: string;
            /** @description A Node's approximate battery charge from its newest device report; absent when unknown. */
            batteryPercent?: number;
            /** @description A Node's charger state from its newest device report; absent when unknown. */
            charging?: components["schemas"]["ChargeState"];
        };
        DeviceList: {
            /** @description Every enrolled Device of the Site, ordered by Device ID. */
            devices: components["schemas"]["DeviceListItem"][];
        };
        /** @description RFC 9457 Problem Details. */
        ProblemDetails: {
            /** @description Stable: urn:coldframe:problem:<slug>. The set grows as operations are added, so it is an x-extensible-enum: a client handles a type it does not know by its status. */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
    };
    responses: {
        /** @description urn:coldframe:problem:validation, or urn:coldframe:problem:idempotency-key-missing when the Idempotency-Key header is absent or empty. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:unauthorized: no valid access token (missing, expired, wrong issuer or audience). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:forbidden: the Site exists, but the caller has no Role on it or a lower one than the operation's minimum. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:site-not-found: no Site has this ID. */
        SiteNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:lot-not-found: no Lot has this ID on this Site, or it was removed (for rename and remove of an unknown ID). urn:coldframe:problem:site-not-found when the Site does not exist. */
        LotNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:idempotency-key-reused: the key was used within 24 h for a request with a different body. Nothing was created. */
        IdempotencyKeyReused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:lot-claimed: a Node is assigned to the Lot. Nothing changed; move or unassign the Node first. */
        LotClaimed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:device-unauthorized: the Device authentication failed (unknown Device, bad signature, timestamp more than 300000 ms off, or a replayed nonce; for deviceIngest also a signer that is not a Hub). */
        DeviceUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:ingest-unavailable: the envelope parsed, but the Server could not commit any of its frames (every frame would be retry). Nothing was acknowledged; the Nodes keep their Readings and resend. */
        IngestUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:site-not-found: no Site has this ID. urn:coldframe:problem:lot-not-found: the Site has no such Lot (unknown, removed, or of another Site); nothing was enrolled. */
        DeviceEnrolmentNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:site-not-found: no Site has this ID. urn:coldframe:problem:device-not-found: the Site has no such Node (unknown, a Hub, or of another Site). urn:coldframe:problem:lot-not-found: the Site has no such Lot (unknown, removed, or of another Site). Nothing changed. */
        DeviceMoveNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:site-not-found: no Site has this ID. urn:coldframe:problem:sensor-not-found: the Site has no such Sensor (unknown, never declared, or of another Site). Nothing changed. */
        SensorNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:calibration-not-delivered: the Calibration is saved, but the Node's Device grain has not acknowledged it yet. The Server delivers it again until it does; send the same request again to see whether it is in force. */
        CalibrationNotDelivered: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:device-on-another-site: the Device is already enrolled on another Site. urn:coldframe:problem:lot-claimed: this Lot already has a Node. urn:coldframe:problem:device-assigned: the Node is in another Lot already; move it instead. Nothing was enrolled or assigned. */
        DeviceEnrolmentConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:identity-provider-unavailable: Keycloak could not be reached. The request stays pending; retry with the same Idempotency-Key. */
        IdentityProviderUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description The Site ID, which is the Keycloak Organization ID. */
        SiteId: string;
        /** @description Chosen by the client per creation; kept 24 h after the request once the creation completes, and until it completes while it is still pending. 1 to 200 printable ASCII characters. */
        IdempotencyKey: string;
        /** @description The Lot ID, a UUIDv7. */
        LotId: string;
        /** @description The Sensor ID, a UUIDv5 of its Device ID, slot and quantity, in lowercase hyphenated form. */
        SensorId: string;
        /** @description The Device ID, 16 lowercase hex digits. */
        DeviceId: components["schemas"]["DeviceId"];
        /** @description The calling Device's ID, 16 lowercase hex digits. */
        DeviceIdHeader: components["schemas"]["DeviceId"];
        /** @description The request time, Unix milliseconds UTC; rejected when more than 300000 ms off the Server clock. */
        DeviceTimestampHeader: string;
        /** @description 16 random bytes as 32 lowercase hex digits; a replayed nonce is rejected. */
        DeviceNonceHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    deviceHeartbeat: {
        parameters: {
            query?: never;
            header: {
                /** @description The calling Device's ID, 16 lowercase hex digits. */
                "X-Coldframe-Device": components["parameters"]["DeviceIdHeader"];
                /** @description The request time, Unix milliseconds UTC; rejected when more than 300000 ms off the Server clock. */
                "X-Coldframe-Timestamp": components["parameters"]["DeviceTimestampHeader"];
                /** @description 16 random bytes as 32 lowercase hex digits; a replayed nonce is rejected. */
                "X-Coldframe-Nonce": components["parameters"]["DeviceNonceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description The heartbeat is recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["DeviceUnauthorized"];
        };
    };
    deviceIngest: {
        parameters: {
            query?: never;
            header: {
                /** @description The calling Device's ID, 16 lowercase hex digits. */
                "X-Coldframe-Device": components["parameters"]["DeviceIdHeader"];
                /** @description The request time, Unix milliseconds UTC; rejected when more than 300000 ms off the Server clock. */
                "X-Coldframe-Timestamp": components["parameters"]["DeviceTimestampHeader"];
                /** @description 16 random bytes as 32 lowercase hex digits; a replayed nonce is rejected. */
                "X-Coldframe-Nonce": components["parameters"]["DeviceNonceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description The envelope parsed. Each frame has its own status; a frame that failed does not affect the others. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["DeviceUnauthorized"];
            503: components["responses"]["IngestUnavailable"];
        };
    };
    getEnrolmentKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The enrolment key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrolmentKey"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's Sites. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSite: {
        parameters: {
            query?: never;
            header: {
                /** @description Chosen by the client per creation; kept 24 h after the request once the creation completes, and until it completes while it is still pending. 1 to 200 printable ASCII characters. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSiteRequest"];
            };
        };
        responses: {
            /** @description The Site exists and the caller is its Owner. */
            201: {
                headers: {
                    /** @description The Site, /sites/{siteId}. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["IdempotencyKeyReused"];
            503: components["responses"]["IdentityProviderUnavailable"];
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Site. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SiteNotFound"];
        };
    };
    renameSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameSiteRequest"];
            };
        };
        responses: {
            /** @description The renamed Site. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SiteNotFound"];
            503: components["responses"]["IdentityProviderUnavailable"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Site's Devices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SiteNotFound"];
        };
    };
    enrolDevice: {
        parameters: {
            query?: never;
            header: {
                /** @description Chosen by the client per creation; kept 24 h after the request once the creation completes, and until it completes while it is still pending. 1 to 200 printable ASCII characters. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrolDeviceRequest"];
            };
        };
        responses: {
            /** @description The Device is enrolled on the Site. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["DeviceEnrolmentNotFound"];
            409: components["responses"]["DeviceEnrolmentConflict"];
            422: components["responses"]["IdempotencyKeyReused"];
        };
    };
    moveDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
                /** @description The Device ID, 16 lowercase hex digits. */
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveDeviceRequest"];
            };
        };
        responses: {
            /** @description The Node is on the Lot now. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["DeviceMoveNotFound"];
            409: components["responses"]["LotClaimed"];
        };
    };
    unassignDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
                /** @description The Device ID, 16 lowercase hex digits. */
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Node is on no Lot now. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["DeviceMoveNotFound"];
        };
    };
    getSensorCalibration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
                /** @description The Sensor ID, a UUIDv5 of its Device ID, slot and quantity, in lowercase hyphenated form. */
                sensorId: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Calibration state and the recent stored Readings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationState"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SensorNotFound"];
        };
    };
    calibrateSensor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
                /** @description The Sensor ID, a UUIDv5 of its Device ID, slot and quantity, in lowercase hyphenated form. */
                sensorId: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrateSensorRequest"];
            };
        };
        responses: {
            /** @description The points are saved: the Calibration in force, and the point still waiting for its partner, if any. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Calibration"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SensorNotFound"];
            503: components["responses"]["CalibrationNotDelivered"];
        };
    };
    getSensorThresholds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
                /** @description The Sensor ID, a UUIDv5 of its Device ID, slot and quantity, in lowercase hyphenated form. */
                sensorId: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Thresholds in force. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorThresholds"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SensorNotFound"];
        };
    };
    setSensorThresholds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
                /** @description The Sensor ID, a UUIDv5 of its Device ID, slot and quantity, in lowercase hyphenated form. */
                sensorId: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSensorThresholdsRequest"];
            };
        };
        responses: {
            /** @description The Thresholds in force after the request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorThresholds"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SensorNotFound"];
        };
    };
    listLots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Site's Lots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SiteNotFound"];
        };
    };
    createLot: {
        parameters: {
            query?: never;
            header: {
                /** @description Chosen by the client per creation; kept 24 h after the request once the creation completes, and until it completes while it is still pending. 1 to 200 printable ASCII characters. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLotRequest"];
            };
        };
        responses: {
            /** @description The Lot exists on the Site. */
            201: {
                headers: {
                    /** @description The Lot, /sites/{siteId}/lots/{lotId}. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lot"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SiteNotFound"];
            422: components["responses"]["IdempotencyKeyReused"];
        };
    };
    getLot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
                /** @description The Lot ID, a UUIDv7. */
                lotId: components["parameters"]["LotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Lot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lot"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["LotNotFound"];
        };
    };
    removeLot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
                /** @description The Lot ID, a UUIDv7. */
                lotId: components["parameters"]["LotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Lot is removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["LotNotFound"];
            409: components["responses"]["LotClaimed"];
        };
    };
    renameLot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
                /** @description The Lot ID, a UUIDv7. */
                lotId: components["parameters"]["LotId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameLotRequest"];
            };
        };
        responses: {
            /** @description The renamed Lot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lot"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["LotNotFound"];
        };
    };
    getLotHistory: {
        parameters: {
            query: {
                /** @description The quantity to read. */
                quantity: components["schemas"]["SensorQuantity"];
                /** @description Start of the window, ISO-8601 UTC. Defaults to to minus 30 days. */
                from?: string;
                /** @description End of the window, ISO-8601 UTC. Defaults to now. */
                to?: string;
                /** @description The nextCursor of the previous page; opaque. */
                cursor?: string;
                /** @description The most days in a page. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
                /** @description The Lot ID, a UUIDv7. */
                lotId: components["parameters"]["LotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the Lot's daily history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LotHistory"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["LotNotFound"];
        };
    };
}
