/* eslint-disable -- generated code keeps openapi-typescript's own style */
/**
 * Generated by openapi-typescript from packages/openapi/coldframe.openapi.json.
 * Do not edit: run `pnpm --filter @coldframe/api-client generate`.
 */

export type paths = {
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the Sites the caller holds a Membership on, with the caller's Role
         * @description Only Active Sites. Ordered by creation (oldest first, then by Site ID); clients show them in this order and never re-sort. An empty list means the caller has no Membership.
         */
        get: operations["listSites"];
        put?: never;
        /**
         * Create a Site with the caller as its Owner
         * @description Idempotent per caller and Idempotency-Key for 24 h: a retry returns the original result, and a key reused with a different name is refused.
         */
        post: operations["createSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{siteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a Site with the caller's Role */
        get: operations["getSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /**
         * @description A Role on one Site, ordered Owner > Administrator > Member.
         * @enum {string}
         */
        SiteRole: "Owner" | "Administrator" | "Member";
        CreateSiteRequest: {
            /** @description The Site name. Trimmed; 1 to 100 characters after trimming. */
            name: string;
        };
        Site: {
            /**
             * Format: uuid
             * @description The Site ID.
             */
            id: string;
            /** @description The Site name. */
            name: string;
            role: components["schemas"]["SiteRole"];
        };
        SiteList: {
            /** @description In the Server's order: creation time, then Site ID. */
            sites: components["schemas"]["Site"][];
        };
        /** @description RFC 9457 Problem Details. */
        ProblemDetails: {
            /**
             * @description Stable: urn:coldframe:problem:<slug>.
             * @enum {string}
             */
            type: "urn:coldframe:problem:unauthorized" | "urn:coldframe:problem:forbidden" | "urn:coldframe:problem:site-not-found" | "urn:coldframe:problem:validation" | "urn:coldframe:problem:idempotency-key-missing" | "urn:coldframe:problem:idempotency-key-reused" | "urn:coldframe:problem:identity-provider-unavailable";
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
    };
    responses: {
        /** @description urn:coldframe:problem:validation, or urn:coldframe:problem:idempotency-key-missing when the Idempotency-Key header is absent or empty. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:unauthorized: no valid access token (missing, expired, wrong issuer or audience). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:forbidden: the Site exists, but the caller has no Role on it or a lower one than the operation's minimum. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:site-not-found: no Site has this ID. */
        SiteNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:idempotency-key-reused: the key was used within 24 h for a request with a different name. Nothing was created. */
        IdempotencyKeyReused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description urn:coldframe:problem:identity-provider-unavailable: Keycloak could not be reached. The request stays pending; retry with the same Idempotency-Key. */
        IdentityProviderUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description The Site ID, which is the Keycloak Organization ID. */
        SiteId: string;
        /** @description Chosen by the client per creation; kept 24 h after the request once the creation completes, and until it completes while it is still pending. 1 to 200 printable ASCII characters. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    listSites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's Sites. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSite: {
        parameters: {
            query?: never;
            header: {
                /** @description Chosen by the client per creation; kept 24 h after the request once the creation completes, and until it completes while it is still pending. 1 to 200 printable ASCII characters. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSiteRequest"];
            };
        };
        responses: {
            /** @description The Site exists and the caller is its Owner. */
            201: {
                headers: {
                    /** @description The Site, /sites/{siteId}. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["IdempotencyKeyReused"];
            503: components["responses"]["IdentityProviderUnavailable"];
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Site ID, which is the Keycloak Organization ID. */
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Site. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SiteNotFound"];
        };
    };
}
