//! Coldframe wire messages, generated from `packages/proto` with micropb (AD-10).
//!
//! `no_std` without `alloc`: every string, bytes and repeated field is a heapless container with
//! a fixed capacity, so each message has a compile-time `MAX_SIZE`.
//!
//! - [`setup_v1`]: the BLE setup protocol, `coldframe.setup.v1` (AD-25). Module path in the
//!   generated code: `coldframe_::setup_::v1_`; the `oneof body` is `SetupMessage_::Body`.
//! - [`device_v1`]: sealed Device frames and downlinks, `coldframe.device.v1` (AD-9, AD-12):
//!   `SealedEnvelope`, `NodeFrame` (its `oneof measured` is `NodeFrame_::Measured`), `Downlink`
//!   and `SpecificationSet`, sized for a Node with four Sensors.
//! - [`radio`]: the Node ⇄ Hub ESP-NOW messages (AD-9): one kind byte, then a fixed body or the
//!   bytes of a `SealedEnvelope`.
//! - [`encode`] and [`decode`]: one message to or from a byte slice; [`encode_node_frame`] for a
//!   `NodeFrame` in field-number order.
//!
//! Types that can hold a Wi-Fi password (`WifiConfig`, `SetupMessage` and its `Body`) do not
//! implement `Debug`, so a password cannot reach a log through `{:?}`.

#![no_std]

use core::fmt;

use micropb::size::max_encoded_size;
use micropb::{MessageDecode, MessageEncode, PbEncoder};

#[allow(
    clippy::all,
    clippy::pedantic,
    nonstandard_style,
    unused,
    missing_docs,
    reason = "generated by micropb-gen"
)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/protocol.rs"));
}

pub mod radio;

pub use micropb;

/// `coldframe.setup.v1`: the BLE setup protocol.
pub use generated::coldframe_::setup_::v1_ as setup_v1;

/// `coldframe.device.v1`: sealed Device frames and downlinks.
pub use generated::coldframe_::device_::v1_ as device_v1;

/// The wire major every message carries in `protocol_version`.
pub const PROTOCOL_VERSION: u32 = 1;

/// Length of the ChaCha20-Poly1305 tag a sealed `SetupMessage` carries.
const SETUP_TAG_LENGTH: usize = 16;

/// The largest encoded `SetupMessage` (a full 16-network scan list).
pub const SETUP_MESSAGE_MAX_SIZE: usize = max_encoded_size::<setup_v1::SetupMessage>();

/// The largest encoded `SealedSetupMessage`.
pub const SEALED_SETUP_MESSAGE_MAX_SIZE: usize = max_encoded_size::<setup_v1::SealedSetupMessage>();

/// The largest encoded `SessionHello`.
pub const SESSION_HELLO_MAX_SIZE: usize = max_encoded_size::<setup_v1::SessionHello>();

/// The largest encoded `SessionHelloReply`.
pub const SESSION_HELLO_REPLY_MAX_SIZE: usize = max_encoded_size::<setup_v1::SessionHelloReply>();

/// Capacity of `SealedSetupMessage.ciphertext`, as `build.rs` configures it.
pub const SEALED_CIPHERTEXT_CAPACITY: usize =
    include!(concat!(env!("OUT_DIR"), "/sealed_capacity.rs"));

/// Capacity of `SealedEnvelope.ciphertext`, as `build.rs` configures it.
pub const ENVELOPE_CIPHERTEXT_CAPACITY: usize =
    include!(concat!(env!("OUT_DIR"), "/envelope_capacity.rs"));

/// The largest encoded `SealedEnvelope` the generated type can hold.
pub const SEALED_ENVELOPE_MAX_SIZE: usize = max_encoded_size::<device_v1::SealedEnvelope>();

/// The largest encoded `NodeFrame` the generated type can hold (every varint at its widest).
pub const NODE_FRAME_MAX_SIZE: usize = max_encoded_size::<device_v1::NodeFrame>();

/// The largest encoded `Downlink` the generated type can hold.
pub const DOWNLINK_MAX_SIZE: usize = max_encoded_size::<device_v1::Downlink>();

/// The largest encoded `SpecificationSet` the generated type can hold.
pub const SPECIFICATION_SET_MAX_SIZE: usize = max_encoded_size::<device_v1::SpecificationSet>();

// The ciphertext field holds whatever fits one radio payload: an envelope has at least the
// protocol_version (2 bytes), the Device ID (10) and the ciphertext's own header (2).
const _: () = assert!(ENVELOPE_CIPHERTEXT_CAPACITY + 14 >= radio::ENVELOPE_MAX);

// The ciphertext field holds exactly the largest SetupMessage plus its tag.
const _: () = assert!(SEALED_CIPHERTEXT_CAPACITY == SETUP_MESSAGE_MAX_SIZE + SETUP_TAG_LENGTH);

/// Why a message could not be encoded or decoded. Carries no message content.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CodecError {
    /// The output buffer is too small for the encoded message.
    BufferTooSmall,
    /// The bytes are not a valid encoding: truncated, a bad wire type, invalid UTF-8, or a field
    /// over its fixed capacity.
    Malformed,
}

impl fmt::Display for CodecError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::BufferTooSmall => "output buffer too small",
            Self::Malformed => "malformed message",
        })
    }
}

impl core::error::Error for CodecError {}

/// Encodes `message` into the front of `out`; returns the encoded length.
///
/// # Errors
///
/// [`CodecError::BufferTooSmall`] when `out` cannot hold it.
pub fn encode<M: MessageEncode>(message: &M, out: &mut [u8]) -> Result<usize, CodecError> {
    let total = out.len();
    let mut rest: &mut [u8] = out;
    message
        .encode(&mut PbEncoder::new(&mut rest))
        .map_err(|()| CodecError::BufferTooSmall)?;
    Ok(total - rest.len())
}

/// Decodes one message of type `M` from all of `bytes`.
///
/// # Errors
///
/// [`CodecError::Malformed`] when `bytes` is not a valid encoding of `M` within its capacities.
pub fn decode<M: MessageDecode + Default>(bytes: &[u8]) -> Result<M, CodecError> {
    let mut message = M::default();
    message
        .decode_from_bytes(bytes)
        .map_err(|_| CodecError::Malformed)?;
    Ok(message)
}

/// Encodes a `NodeFrame` with its fields in field-number order; returns the encoded length.
///
/// micropb writes a `oneof` after every other field, so [`encode`] would put `measured` (fields
/// 5 and 6) last. Any Protobuf decoder reads both orders alike, but the shared vector of
/// `packages/crypto-spec` pins the bytes other implementations produce, and those are in
/// field-number order. This writes the frame in three parts (fields 1 to 4, `measured`, fields 7
/// to 11), whose concatenation is that encoding.
///
/// # Errors
///
/// [`CodecError::BufferTooSmall`] when `out` cannot hold it.
pub fn encode_node_frame(
    frame: &device_v1::NodeFrame,
    out: &mut [u8],
) -> Result<usize, CodecError> {
    let head = device_v1::NodeFrame {
        protocol_version: frame.protocol_version,
        spec_hash: frame.spec_hash.clone(),
        boot_id: frame.boot_id,
        uptime_ms: frame.uptime_ms,
        ..device_v1::NodeFrame::default()
    };
    let measured = device_v1::NodeFrame {
        measured: frame.measured.clone(),
        ..device_v1::NodeFrame::default()
    };
    let mut tail = frame.clone();
    tail.protocol_version = 0;
    tail.spec_hash.clear();
    tail.boot_id = 0;
    tail.uptime_ms = 0;
    tail.measured = None;

    let mut length = 0;
    for part in [&head, &measured, &tail] {
        let rest = out.get_mut(length..).ok_or(CodecError::BufferTooSmall)?;
        length += encode(part, rest)?;
    }
    Ok(length)
}
