import { existsSync, readdirSync, readFileSync } from 'node:fs';

import { toKotlinColor, toSwiftColor } from './color.ts';
import { ICON_NAMES, loadIcons, parsePathData, VIEWPORT_SIZE, type IconName } from './icons.ts';
import {
  cssColorVar,
  cssRadiusVar,
  cssSpacingVar,
  kotlinConstName,
  memberName,
  radiusMemberName,
  spacingMemberName,
  swiftCaseName,
} from './naming.ts';
import { fromRoot, generatedDirs, outputPaths, repoRoot } from './paths.ts';
import { loadTokens, type Theme, type TokensFile } from './tokens.ts';
import { fontStack, isCapped, MAX_SCALE, webFontSize } from './typography.ts';

export interface Inputs {
  tokens: TokensFile;
  icons: Record<IconName, string>;
}

export function loadInputs(root = repoRoot): Inputs {
  return { tokens: loadTokens(root), icons: loadIcons(root) };
}

const REGENERATE = 'pnpm --filter @coldframe/design-tokens run generate';
const HEADER = 'Generated by packages/design-tokens/scripts/generate.ts. Do not edit.';
const REGENERATE_HINT = `Regenerate with \`${REGENERATE}\`.`;
const CARBON = '@carbon/icons 11.89.0 (Apache-2.0)';

/** Formats a number the way every output writes it: no trailing zeros, no exponent. */
function num(value: number): string {
  return String(value);
}

/** Splits path data into chunks of at most `width` characters, at spaces, keeping each separator. */
function chunkPathData(data: string, width: number): string[] {
  const chunks: string[] = [];
  let current = '';
  for (const token of data.split(' ')) {
    const next = current === '' ? token : `${current} ${token}`;
    if (next.length > width && current !== '') {
      chunks.push(`${current} `);
      current = token;
    } else {
      current = next;
    }
  }
  chunks.push(current);
  return chunks;
}

// ---------- Web ----------

function cssColors(tokens: TokensFile, theme: Theme, indent: string): string[] {
  return Object.entries(tokens.colors).map(([name, token]) => `${indent}${cssColorVar(name)}: ${token[theme]};`);
}

function renderTokensCss(tokens: TokensFile): string {
  const lines = [`/* ${HEADER} ${REGENERATE_HINT} */`, '', ':root,', '[data-theme="light"] {', '  color-scheme: light;'];
  lines.push(...cssColors(tokens, 'light', '  '));
  lines.push('');
  lines.push(`  --cf-font-sans: ${fontStack('Ubuntu')};`);
  lines.push(`  --cf-font-sans-condensed: ${fontStack('Ubuntu Condensed')};`);
  lines.push(`  --cf-font-mono: ${fontStack('Ubuntu Mono')};`);
  lines.push('');
  for (const [name, value] of Object.entries(tokens.spacing)) {
    lines.push(`  ${cssSpacingVar(name)}: ${num(value)}px;`);
  }
  lines.push('');
  for (const [name, value] of Object.entries(tokens.rounded)) {
    lines.push(`  ${cssRadiusVar(name)}: ${num(value)}px;`);
  }
  for (const [name, role] of Object.entries(tokens.typography)) {
    const prefix = `  --cf-type-${name}`;
    lines.push('');
    lines.push(`${prefix}-font-family: ${fontStack(role.fontFamily)};`);
    lines.push(`${prefix}-font-size: ${webFontSize(role.fontSize)};`);
    lines.push(`${prefix}-font-weight: ${num(role.fontWeight)};`);
    lines.push(`${prefix}-line-height: ${num(role.lineHeight)};`);
    lines.push(`${prefix}-letter-spacing: ${num(role.letterSpacingEm)}em;`);
    lines.push(`${prefix}-text-transform: ${role.uppercase ? 'uppercase' : 'none'};`);
  }
  lines.push('}', '', '[data-theme="dark"] {', '  color-scheme: dark;');
  lines.push(...cssColors(tokens, 'dark', '  '));
  lines.push('}', '', '/* "System": no data-theme attribute, so the platform setting decides. */');
  lines.push('@media (prefers-color-scheme: dark) {', '  :root:not([data-theme="light"]) {', '    color-scheme: dark;');
  lines.push(...cssColors(tokens, 'dark', '    '));
  lines.push('  }', '}', '');
  return lines.join('\n');
}

const FONT_FACES = [
  { family: 'Ubuntu', weight: 300, file: 'Ubuntu-Light.ttf' },
  { family: 'Ubuntu', weight: 400, file: 'Ubuntu-Regular.ttf' },
  { family: 'Ubuntu Condensed', weight: 400, file: 'UbuntuCondensed-Regular.ttf' },
  { family: 'Ubuntu Mono', weight: 400, file: 'UbuntuMono-Regular.ttf' },
] as const;

function renderFontsCss(): string {
  const lines = [
    `/* ${HEADER} ${REGENERATE_HINT} */`,
    '/* Ubuntu fonts, Ubuntu Font Licence 1.0 (packages/design-tokens/fonts/UFL.txt), served by the app itself. */',
  ];
  for (const face of FONT_FACES) {
    lines.push(
      '',
      '@font-face {',
      `  font-family: '${face.family}';`,
      '  font-style: normal;',
      `  font-weight: ${num(face.weight)};`,
      '  font-display: swap;',
      `  src: url('../../fonts/${face.file}') format('truetype');`,
      '}',
    );
  }
  lines.push('');
  return lines.join('\n');
}

function renderSvg(pathData: string): string {
  return [
    `<!-- ${HEADER} ${REGENERATE_HINT} Source: ${CARBON}. -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${num(VIEWPORT_SIZE)} ${num(VIEWPORT_SIZE)}" fill="currentColor"><path d="${pathData}"/></svg>`,
    '',
  ].join('\n');
}

function tsKey(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : `'${name}'`;
}

function renderTsIndex({ tokens, icons }: Inputs): string {
  const lines = [`// ${HEADER}`, `// ${REGENERATE_HINT}`, ''];
  lines.push('/** Colour tokens of DESIGN.md: `#RRGGBB` or `#RRGGBBAA` per theme. */', 'export const colors = {');
  for (const [name, token] of Object.entries(tokens.colors)) {
    lines.push(`  ${tsKey(name)}: { light: '${token.light}', dark: '${token.dark}' },`);
  }
  lines.push('} as const;', '', 'export type ColorName = keyof typeof colors;', '');
  lines.push(
    '/** Typography roles; sizes in px, `cssFontSize` in rem with the 2× cap on roles of 36 px and more. */',
    'export const typography = {',
  );
  for (const [name, role] of Object.entries(tokens.typography)) {
    lines.push(
      `  ${tsKey(name)}: {`,
      `    fontFamily: '${role.fontFamily}',`,
      `    fontSize: ${num(role.fontSize)},`,
      `    fontWeight: ${num(role.fontWeight)},`,
      `    lineHeight: ${num(role.lineHeight)},`,
      `    letterSpacingEm: ${num(role.letterSpacingEm)},`,
      `    uppercase: ${String(role.uppercase)},`,
      `    iosTextStyle: '${role.iosTextStyle}',`,
      `    cssFontSize: '${webFontSize(role.fontSize)}',`,
      '  },',
    );
  }
  lines.push('} as const;', '', 'export type TypeRoleName = keyof typeof typography;', '');
  lines.push('/** Spacing in px. */', 'export const spacing = {');
  for (const [name, value] of Object.entries(tokens.spacing)) {
    lines.push(`  '${name}': ${num(value)},`);
  }
  lines.push('} as const;', '', '/** Corner radii in px; every one is 0. */', 'export const rounded = {');
  for (const [name, value] of Object.entries(tokens.rounded)) {
    lines.push(`  ${tsKey(name)}: ${num(value)},`);
  }
  lines.push('} as const;', '');
  lines.push(`/** Carbon icon names (${CARBON}). */`, 'export const iconNames = [');
  for (const name of ICON_NAMES) {
    lines.push(`  '${name}',`);
  }
  lines.push('] as const;', '', 'export type IconName = (typeof iconNames)[number];', '');
  lines.push(`export const iconViewBox = '0 0 ${num(VIEWPORT_SIZE)} ${num(VIEWPORT_SIZE)}';`, '');
  lines.push(
    '/** Icon geometry as absolute M/L/C/Z path data in the 32×32 viewport; it carries no colour. */',
    'export const icons: Readonly<Record<IconName, string>> = {',
  );
  for (const name of ICON_NAMES) {
    lines.push(`  '${name}': '${icons[name]}',`);
  }
  lines.push('};', '');
  return lines.join('\n');
}

// ---------- Swift ----------

function swiftIdentifier(name: string): string {
  return ['default', 'case', 'class', 'enum', 'struct', 'let', 'var', 'func'].includes(name) ? `\`${name}\`` : name;
}

function swiftFile(body: string[]): string {
  return [`// ${HEADER}`, `// ${REGENERATE_HINT}`, '', ...body, ''].join('\n');
}

function renderSwiftColors(tokens: TokensFile): string {
  const body = ['/// Colour tokens of DESIGN.md, light and dark.', 'public enum ColorTokens {'];
  for (const [name, token] of Object.entries(tokens.colors)) {
    body.push(
      `  public static let ${memberName(name)} = ThemedColor(light: ${toSwiftColor(token.light)}, dark: ${toSwiftColor(token.dark)})`,
    );
  }
  body.push('', '  /// Every colour token by its DESIGN.md name.', '  public static let all: [String: ThemedColor] = [');
  for (const name of Object.keys(tokens.colors)) {
    body.push(`    "${name}": ${memberName(name)},`);
  }
  body.push('  ]', '}');
  return swiftFile(body);
}

function renderSwiftTypography(tokens: TokensFile): string {
  const body = [
    '/// Typography roles of DESIGN.md. Sizes are points at the default text size; they scale with',
    '/// Dynamic Type relative to `textStyle`, capped at `maximumPointSize` when there is one.',
    'public enum Typography {',
  ];
  for (const [name, role] of Object.entries(tokens.typography)) {
    body.push(
      `  public static let ${memberName(name)} = TypeRole(`,
      `    fontFamily: "${role.fontFamily}",`,
      `    size: ${num(role.fontSize)},`,
      `    weight: ${num(role.fontWeight)},`,
      `    lineHeight: ${num(role.lineHeight)},`,
      `    letterSpacingEm: ${num(role.letterSpacingEm)},`,
      `    uppercase: ${String(role.uppercase)},`,
      `    textStyle: .${role.iosTextStyle},`,
      `    maximumPointSize: ${isCapped(role.fontSize) ? num(role.fontSize * MAX_SCALE) : 'nil'}`,
      '  )',
    );
  }
  body.push('', '  /// Every role by its DESIGN.md name.', '  public static let all: [String: TypeRole] = [');
  for (const name of Object.keys(tokens.typography)) {
    body.push(`    "${name}": ${memberName(name)},`);
  }
  body.push('  ]', '}');
  return swiftFile(body);
}

function renderSwiftSpacing(tokens: TokensFile): string {
  const body = ['/// Spacing tokens of DESIGN.md, in points.', 'public enum Spacing {'];
  for (const [name, value] of Object.entries(tokens.spacing)) {
    body.push(`  public static let ${spacingMemberName(name)}: Double = ${num(value)}`);
  }
  body.push('}');
  return swiftFile(body);
}

function renderSwiftRadius(tokens: TokensFile): string {
  const body = ['/// Corner radii of DESIGN.md, in points. Everything is square.', 'public enum Radius {'];
  for (const [name, value] of Object.entries(tokens.rounded)) {
    body.push(`  public static let ${swiftIdentifier(radiusMemberName(name))}: Double = ${num(value)}`);
  }
  body.push('}');
  return swiftFile(body);
}

function renderSwiftIcons({ icons }: Inputs): string {
  const body = [
    `/// Carbon icons (${CARBON}), geometry only.`,
    'public enum CarbonIcon: String, CaseIterable, Sendable {',
  ];
  for (const name of ICON_NAMES) {
    body.push(`  case ${swiftCaseName(name)} = "${name}"`);
  }
  body.push(
    '',
    '  /// Absolute M/L/C/Z path data in the 32×32 viewport; parse it with `IconPath.parse`.',
    '  public var pathData: String {',
    '    switch self {',
  );
  for (const name of ICON_NAMES) {
    const chunks = chunkPathData(icons[name], 80);
    body.push(`    case .${swiftCaseName(name)}:`, '      """');
    chunks.forEach((chunk, index) => {
      body.push(`      ${chunk}${index < chunks.length - 1 ? '\\' : ''}`);
    });
    body.push('      """');
  }
  body.push('    }', '  }', '}');
  return swiftFile(body);
}

// ---------- Kotlin ----------

const KOTLIN_PACKAGE = 'com.escendit.coldframe.designtokens';

function kotlinFile(body: string[]): string {
  return [`// ${HEADER}`, `// ${REGENERATE_HINT}`, '', `package ${KOTLIN_PACKAGE}`, '', ...body, ''].join('\n');
}

function kotlinFloat(value: number): string {
  return `${num(value)}f`;
}

function renderKotlinColors(tokens: TokensFile): string {
  const body = [
    '/** Colour tokens of DESIGN.md, light and dark, as Android `0xAARRGGBB`. */',
    'public object ColorTokens {',
  ];
  for (const [name, token] of Object.entries(tokens.colors)) {
    body.push(
      `    public val ${memberName(name)}: ThemedColor = ThemedColor(light = ${toKotlinColor(token.light)}, dark = ${toKotlinColor(token.dark)})`,
    );
  }
  body.push('', '    /** Every colour token by its DESIGN.md name. */', '    public val all: Map<String, ThemedColor> =');
  body.push('        mapOf(');
  for (const name of Object.keys(tokens.colors)) {
    body.push(`            "${name}" to ${memberName(name)},`);
  }
  body.push('        )', '}');
  return kotlinFile(body);
}

function renderKotlinTypography(tokens: TokensFile): string {
  const body = [
    '/**',
    ' * Typography roles of DESIGN.md. Sizes are `sp` at font scale 1; roles with a `maxFontScale` stop',
    ' * growing at that scale.',
    ' */',
    'public object Typography {',
  ];
  for (const [name, role] of Object.entries(tokens.typography)) {
    body.push(
      `    public val ${memberName(name)}: TypeRole =`,
      '        TypeRole(',
      `            fontFamily = "${role.fontFamily}",`,
      `            sizeSp = ${kotlinFloat(role.fontSize)},`,
      `            fontWeight = ${num(role.fontWeight)},`,
      `            lineHeight = ${kotlinFloat(role.lineHeight)},`,
      `            letterSpacingEm = ${kotlinFloat(role.letterSpacingEm)},`,
      `            uppercase = ${String(role.uppercase)},`,
      `            maxFontScale = ${isCapped(role.fontSize) ? kotlinFloat(MAX_SCALE) : 'null'},`,
      '        )',
      '',
    );
  }
  body.push('    /** Every role by its DESIGN.md name. */', '    public val all: Map<String, TypeRole> =', '        mapOf(');
  for (const name of Object.keys(tokens.typography)) {
    body.push(`            "${name}" to ${memberName(name)},`);
  }
  body.push('        )', '}');
  return kotlinFile(body);
}

function renderKotlinConstants(kdoc: string, objectName: string, entries: [string, number][]): string {
  const body = [`/** ${kdoc} */`, `public object ${objectName} {`];
  for (const [name, value] of entries) {
    body.push(`    public const val ${kotlinConstName(name)}: Float = ${kotlinFloat(value)}`);
  }
  body.push('}');
  return kotlinFile(body);
}

function renderKotlinIcons({ icons }: Inputs): string {
  const body = [
    '/**',
    ` * Carbon icons (${CARBON}), geometry only.`,
    ' *',
    ' * [pathData] is absolute M/L/C/Z path data in the 32×32 viewport; parse it with [IconPath.parse].',
    ' */',
    'public enum class CarbonIcon(',
    '    public val carbonName: String,',
    '    public val pathData: String,',
    ') {',
  ];
  for (const name of ICON_NAMES) {
    const chunks = chunkPathData(icons[name], 80);
    body.push(`    ${kotlinConstName(memberName(name))}(`, `        "${name}",`);
    chunks.forEach((chunk, index) => {
      const indent = index === 0 ? '        ' : '            ';
      body.push(`${indent}"${chunk}"${index < chunks.length - 1 ? ' +' : ','}`);
    });
    body.push('    ),');
  }
  body.push('}');
  return kotlinFile(body);
}

// ---------- All ----------

/** Every generated file, keyed by its path relative to the repository root. */
export function renderOutputs(inputs: Inputs): Map<string, string> {
  const { tokens } = inputs;
  for (const name of ICON_NAMES) {
    parsePathData(inputs.icons[name]);
  }
  const outputs = new Map<string, string>([
    [outputPaths.tokensCss, renderTokensCss(tokens)],
    [outputPaths.fontsCss, renderFontsCss()],
    [outputPaths.tsIndex, renderTsIndex(inputs)],
    [outputPaths.swiftColors, renderSwiftColors(tokens)],
    [outputPaths.swiftTypography, renderSwiftTypography(tokens)],
    [outputPaths.swiftSpacing, renderSwiftSpacing(tokens)],
    [outputPaths.swiftRadius, renderSwiftRadius(tokens)],
    [outputPaths.swiftIcons, renderSwiftIcons(inputs)],
    [outputPaths.kotlinColors, renderKotlinColors(tokens)],
    [outputPaths.kotlinTypography, renderKotlinTypography(tokens)],
    [
      outputPaths.kotlinSpacing,
      renderKotlinConstants(
        'Spacing tokens of DESIGN.md, in dp.',
        'Spacing',
        Object.entries(tokens.spacing).map(([name, value]) => [spacingMemberName(name), value]),
      ),
    ],
    [
      outputPaths.kotlinRadius,
      renderKotlinConstants(
        'Corner radii of DESIGN.md, in dp. Everything is square.',
        'Radius',
        Object.entries(tokens.rounded).map(([name, value]) => [radiusMemberName(name), value]),
      ),
    ],
    [outputPaths.kotlinIcons, renderKotlinIcons(inputs)],
  ]);
  for (const name of ICON_NAMES) {
    outputs.set(`${outputPaths.iconsDir}/${name}.svg`, renderSvg(inputs.icons[name]));
  }
  return outputs;
}

/**
 * Paths whose committed content differs from `outputs`, is missing, or sits in a generated
 * folder without being generated. Empty when everything is fresh.
 */
export function findStale(root: string, outputs: ReadonlyMap<string, string>): string[] {
  const stale: string[] = [];
  for (const [path, content] of outputs) {
    const file = fromRoot(path, root);
    if (!existsSync(file) || readFileSync(file, 'utf8') !== content) {
      stale.push(path);
    }
  }
  for (const dir of generatedDirs) {
    const absolute = fromRoot(dir, root);
    if (!existsSync(absolute)) continue;
    for (const entry of readdirSync(absolute, { withFileTypes: true })) {
      const path = `${dir}/${entry.name}`;
      if (entry.isFile() && !outputs.has(path)) {
        stale.push(path);
      }
    }
  }
  return stale;
}
